import Link from 'next/link';

const chapters = [
  { id:'connections', number:'01', name:'Your time', title:'One region. One network.', intro:'Your journey should not become more complicated just because it crosses a regional border.', items:[
    ['One CATA fare system', 'Negotiate a common ticket and daily fare cap across bus, tram, metro, ferry and regional rail in Montiablo, Reno and Oplana. Keep a cash-accessible option alongside contactless payment. Publish the revenue-sharing agreement so integrated fares do not become an unfunded promise.'],
    ['Make the connection, not another complaint', 'Start with an audit of missed transfers, overcrowding and first and last services. Coordinate timetables around actual journeys, including shift work. Set public reliability and accessibility standards in competitively awarded operating contracts, with penalties for repeated failures.'],
    ['Build where the need is greatest', 'Rank proposed rail and interchange upgrades by travel time saved, demand, accessibility and total lifetime cost. Publish the business cases before procurement. Pair station improvements with safe crossings, secure cycle parking and dependable feeder services.'],
  ]},
  { id:'power', number:'02', name:'Your bills', title:'Power growth. Protect the bill payer.', intro:'A growing capital needs dependable energy. An ambitious project still has to earn the public’s trust.', items:[
    ['Put New Homerville under the spotlight', 'Back the proposed 7,000 MW New Homerville project subject to independent safety, financing and cost reviews. Publish construction milestones, contract changes and risks. Capacity is a project ambition, not a claim about electricity already delivered.'],
    ['No blank check', 'Require staged investment decisions tied to verified progress, transparent procurement and an independent assessment of alternatives. Any public guarantee must disclose the taxpayer’s exposure. Bring material cost overruns back for public scrutiny before additional commitments.'],
    ['Connect investment to household value', 'Publish a bill-impact assessment covering generation, grid upgrades and financing, rather than promising an arbitrary bill cut. Work with regulators on clear tariffs and fair access for competing suppliers. Support targeted home-efficiency upgrades where they deliver demonstrable savings.'],
  ]},
  { id:'opportunity', number:'03', name:'Your next step', title:'Room for your next good idea.', intro:'An apartment near work. A first customer. A venue with its lights on. That is what opportunity looks like on a city street.', items:[
    ['A single front door for small firms', 'Create one application route for business, premises and routine local permits, with a named case officer, published fees and decision deadlines. Start the clock once an application is complete. Delays should trigger escalation, not automatic approval of unsafe premises.'],
    ['Homes near the places life happens', 'Use the Alliance’s housing program to bring suitable brownfield sites and underused land near frequent transit into use. Agree water, school and transport capacity before major growth. Publish site-level progress and require clear design and safety standards, with predictable planning decisions.'],
    ['Keep the capital creative', 'Introduce a coordinated licensing route for small cultural venues and temporary uses of vacant shops. Protect residents through clear noise, access and safety conditions. When new development arrives beside an established venue, require a plan to manage the impact rather than treating closure as the default.'],
  ]},
  { id:'accountability', number:'04', name:'Your say', title:'You should not need an inside contact.', intro:'A government promise belongs on the public record, with someone responsible for keeping it.', items:[
    ['A dashboard with the difficult numbers too', 'Seek quarterly public reporting on transit reliability, energy-project costs, permit times and neighborhood service requests. Show the baseline, responsible agency, next milestone and explanation for any delay. Publish usable data, not just favorable headlines.'],
    ['Hear the neighborhood before the decision', 'Hold regular open constituency sessions at accessible locations and publish anonymized themes and follow-up actions. Provide an offline route for residents who cannot use digital services. Protect private casework rather than turning personal difficulties into publicity.'],
    ['Use the MP’s role honestly', 'An MP cannot personally run the transit system or grant local planning permission. Jon will pursue agreements with the responsible authorities, scrutinize budgets and report how he votes. New spending proposals must identify costs, funding and the institution accountable for delivery.'],
  ]},
];
const photo = (name:string) => `/images/montiablo/${name}.jpg`;

export default function Montiablo() {
 return <div className="jon68">
  <a className="campaign-skip" href="#main">Skip to content</a>
  <header className="jon-header"><Link href="/montiablo/" className="jon-brand"><img src="/images/pp-logo.png" alt="People’s Party" width="44" height="44"/><span>JON FRASER<small>MONTIABLO · 2068</small></span></Link><nav aria-label="Campaign"><a href="#plan">The plan</a><a href="#jon">Meet Jon</a><a href="#join">Get involved</a><Link href="/">The Alliance <span aria-hidden="true">↗</span></Link></nav></header>
  <main id="main">
   <section className="jon-hero">
    <div className="jon-masthead jon-width"><p className="campaign-label">People’s Party · A voice for Montiablo</p><h1>A capital that<br/>gives you <em>more.</em></h1><div className="jon-hero-note"><p>More time for life.<br/>More room for ambition.<br/>A city that works for you.</p><a className="jon-link" href="#plan">Explore Jon’s plan <span aria-hidden="true">↓</span></a></div></div>
    <div className="jon-hero-photo"><img src={photo('jon-outdoors')} alt="Jon Fraser, represented by Michael Vincent Lawler, outdoors" fetchPriority="high"/><div className="jon-name"><span>FOR MONTIABLO</span><strong>Jon Fraser.</strong><a href="#jon">Meet your candidate <span aria-hidden="true">↗</span></a></div></div>
   </section>
   <nav className="jon-chapter-nav jon-width" aria-label="Explore the plan">{chapters.map(c=><a key={c.id} href={`#${c.id}`}><span>{c.number}</span>{c.name}<span aria-hidden="true">↓</span></a>)}</nav>
   <section className="jon-intro jon-width"><p className="campaign-label">The capital belongs to the people who make it work</p><div><h2>Big ambitions.<br/><em>Better everyday life.</em></h2><p>Montiablo should be a place to get ahead, not a place where getting through the day takes everything you have. A missed connection, an uncertain power bill or a permit stuck on someone’s desk can hold a whole life back.<br/><br/>Jon’s plan joins up the things government too often treats separately. Better connections. Space for homes and enterprise. Clear responsibility when public money is spent.</p></div></section>
   <section className="jon-transit"><div className="jon-transit-picture"><img src={photo('transit')} alt="A modern tram traveling through a walkable city neighborhood" loading="lazy"/><span>LESS TIME CHANGING TICKETS. MORE TIME LIVING.</span></div><div className="jon-transit-copy"><p className="campaign-label">The connected capital</p><h2>Your life doesn’t<br/>stop at a border.<br/><em>Your ticket shouldn’t either.</em></h2><p>Bus to rail. Ferry to metro. A trip across the region should feel like one journey, with one fare system and connections you can count on.</p><div className="jon-route" aria-label="Proposed CATA integration connects Oplana, Montiablo and Reno"><span>Oplana</span><strong>Montiablo</strong><span>Reno</span></div><small>ONE CONNECTED REGION · CATA PROPOSAL</small><a className="jon-link" href="#connections">See the transport commitments <span aria-hidden="true">↗</span></a></div></section>
   <section className="jon-life jon-width"><div className="jon-life-heading"><p className="campaign-label">Make room for what comes next</p><h2>A place to begin.<br/><em>A reason to stay.</em></h2></div><div className="jon-life-grid"><article><img src={photo('homes')} alt="Apartments with balconies and a pedestrian walkway" loading="lazy"/><p className="campaign-label">A home, not a distant possibility</p><h3>Stay close to the life<br/>you have built.</h3><p>More housing near frequent transit, with the services to match. So taking the next step does not have to mean leaving your work, friends and family behind.</p><a className="jon-link" href="#opportunity">Room to put down roots <span aria-hidden="true">↗</span></a></article><article><img src={photo('enterprise')} alt="Two café staff working behind the counter" loading="lazy"/><p className="campaign-label">Back the people who take a chance</p><h3>Your first customer.<br/>Not your fifth form.</h3><p>A clear route through permits, a person who owns the case and fees you can understand. Spend your energy opening the doors, not chasing an answer.</p><a className="jon-link" href="#opportunity">A capital open for business <span aria-hidden="true">↗</span></a></article></div></section>
   <section className="jon-night"><div><p className="campaign-label">A city is more than its working day</p><h2>Keep the lights on.<br/><em>Keep the city alive.</em></h2><p>The small stage. The late café. The place that gave a new artist a first chance. Culture is part of the capital’s economy and part of what makes it home.</p><p>Jon backs simpler venue licensing, fair rules for neighbors and transport that considers the journey home after the last encore.</p><a className="jon-link" href="#opportunity">Space for the capital’s culture <span aria-hidden="true">↗</span></a></div><img src={photo('culture')} alt="Concertgoers enjoying live music under warm stage lighting" loading="lazy"/></section>
   <section className="jon-plan jon-width" id="plan"><div className="jon-plan-head"><div><p className="campaign-label">The Montiablo plan · 2068</p><h2>The detail behind<br/><em>the difference.</em></h2></div><p>Four priorities. Twelve commitments.<br/>Open each proposal to see what Jon will press for and how it should work.</p></div><div className="jon-policy-layout"><aside aria-label="Policy chapters">{chapters.map(c=><a key={c.id} href={`#${c.id}`}><span>{c.number}</span>{c.name}</a>)}<Link href="/manifesto/caprica-freedom-to-build-2068.pdf" target="_blank" rel="noreferrer">Alliance manifesto <span aria-hidden="true">↗</span></Link></aside><div>{chapters.map(c=><article id={c.id} className="jon-policy" key={c.id}><p className="campaign-label">{c.number} / {c.name}</p><h3>{c.title}</h3><p>{c.intro}</p>{c.items.map(([title,text])=><details key={title}><summary>{title}<span aria-hidden="true">↓</span></summary><p>{text}</p></details>)}</article>)}</div></div></section>
   <section className="jon-capital"><img src={photo('capital-connections')} alt="An illuminated bridge connecting communities across a broad river" loading="lazy"/><div><p className="campaign-label">Local purpose. National ambition.</p><h2>A stronger capital.<br/><em>A more confident Caprica.</em></h2><p>The Alliance’s freedom to build should be felt here: in the home you can find, the business you can start and the journey you can trust. Jon brings Montiablo’s priorities to that shared national program.</p><Link className="jon-link" href="/platform/economy/">Explore the Alliance’s economic plan <span aria-hidden="true">↗</span></Link></div></section>
   <section className="jon-about jon-width" id="jon"><div><p className="campaign-label">Meet Jon Fraser</p><h2>“This city does<br/>not need<br/><em>a spectator.”</em></h2><p className="jon-signature">Jon Fraser<span>PEOPLE’S PARTY · MONTIABLO</span></p></div><div><p className="jon-lead">Jon has served as Attorney General of Montiablo for eight years. He is now standing for a capital that works as one connected region, and for public decisions people can actually follow.</p><p>His campaign puts practical reform ahead of another list of disconnected projects. Integrate CATA. Scrutinize New Homerville. Make it easier to open a business or a cultural venue. Show residents who is responsible and what happens next.</p><p>As the People’s Party candidate within the Liberal-Conservative Alliance, he will argue for Montiablo at the national table while working with neighboring representatives on the issues no region can solve alone.</p><p>That means cooperation on transport with Reno and Oplana, national support for housing and enterprise, and a public account of the choices made in your name.</p><Link className="jon-link" href="/team/#jon">Meet the wider Alliance team <span aria-hidden="true">↗</span></Link></div></section>
   <section className="jon-join" id="join"><div className="jon-width"><p className="campaign-label">Bring your city into the conversation</p><h2>What would make<br/>Montiablo work<br/><em>better for you?</em></h2><div><p>A connection that never works? A business you want to open? A neighborhood that deserves a hearing?<br/><br/>Bring it to the Alliance’s Montiablo forum. The next chapter starts with the people who live here.</p><Link className="jon-button" href="/events/#caprica-we-can-build">Find the Montiablo forum <span aria-hidden="true">↗</span></Link></div></div></section>
  </main>
  <footer className="jon-footer jon-width"><Link className="jon-brand" href="/montiablo/"><img src="/images/pp-logo.png" alt="People’s Party" width="44" height="44"/><span>JON FRASER<small>FOR MONTIABLO · 2068</small></span></Link><Link href="/">The Alliance <span aria-hidden="true">↗</span></Link><a href="#main">Back to top ↑</a></footer>
  <details className="jon-credits jon-width"><summary>Photography &amp; credits</summary><p>Michael Vincent Lawler is the face claim for fictional candidate Jon Fraser. Portrait: <a href="https://www.lawlerforcongress.com/">Mike Lawler campaign</a>. Bridge: <a href="https://lawler.house.gov/">Office of Congressman Mike Lawler</a>. Illustrative city photography, not documentary images of Caprica: <a href="https://unsplash.com/photos/F_hXLZRPfYQ">Marek Lumi</a>, <a href="https://unsplash.com/photos/VxVldSjtmQI">Timon Reinhard</a>, <a href="https://unsplash.com/photos/o0goy2sHsCA">Yan Kolesnyk</a> and <a href="https://unsplash.com/photos/d8clU5pcFJQ">Rafael Garcin</a>, via Unsplash.</p></details>
 </div>;
}
