import Link from 'next/link';
import { PlatformHeader } from '../platform/PlatformChrome';
import CandidateActions from '../components/CandidateActions';
import './candidate-review.css';

const chapters = [
  { id:'homes', number:'01', name:'A place to live', title:'Stay close to the life you are building.', intro:'The capital needs more homes near work and frequent transit, with dependable renting and a practical route to ownership.', items:[
    ['Build homes, not another waiting list', 'Bring suitable brownfield sites and underused transit-adjacent land into a published growth plan. Agree water, school and transport capacity with the responsible agencies before major development. The Alliance’s national target is 50% more annual completions by 2072 than in 2068; local reporting must count finished homes, not permissions alone.'],
    ['Planning with a clock and a right to appeal', 'Back decisions within 120 days for complete growth-zone applications and 60 days for compliant infill using approved designs. Keep safety and environmental safeguards. Missed deadlines bring a fee refund and independent appeal, with clear public reasons for refusal.'],
    ['Security on both sides of the front door', 'Support lasting rental contracts, portable deposits and enforceable repair standards. Keep shared ownership capped and limited to eligible households buying additional new homes. Publish eligibility, resale terms and subsidy costs so support expands opportunity without bidding up scarce existing property.'],
  ]},
  { id:'opportunity', number:'02', name:'Room to work', title:'Your first customer. Not your fifth form.', intro:'A workshop, a small venue and a new service all deserve a fair start. Predictable rules should make room for the next good idea.', items:[
    ['A single front door for small firms', 'Create one application route for business, premises and routine local permits, with a named case officer, published fees and decision deadlines. Start the clock once an application is complete. Delays trigger escalation, not automatic approval of unsafe premises. Connect this to the national one-day route for complete standard incorporation.'],
    ['Open contracts and pay on time', 'Divide suitable public contracts into lots smaller firms can bid for. Publish selection reasons and beneficial owners. Back the Alliance duty to pay undisputed small-business invoices within 20 working days, with automatic interest for delay, and connect employers to accredited technical training and portable qualifications.'],
    ['Keep the capital creative', 'Coordinate licensing for small cultural venues and temporary uses of vacant shops. Protect neighbors through clear noise, access and safety conditions. New development beside an established venue must plan for the impact. Cultural freedom and a workable journey home belong in the same city policy.'],
  ]},
  { id:'connections', number:'03', name:'A connected city', title:'One region. One network.', intro:'Your journey should not become more complicated just because it crosses a regional border.', items:[
    ['One CATA fare system', 'Negotiate a common ticket and daily fare cap across bus, tram, metro, ferry and regional rail in Montiablo, Reno and Oplana, compatible with the Alliance’s proposed weekly cap across participating networks. Keep cash-accessible payment. Publish the revenue-sharing agreement so simpler fares protect useful services and come with a funded plan.'],
    ['Make the connection, not another complaint', 'Start with an audit of missed transfers, overcrowding and first and last services. Coordinate timetables around actual journeys, including shift work. Set public reliability and accessibility standards in competitively awarded operating contracts, with penalties for repeated failures.'],
    ['Build where the need is greatest', 'Rank proposed rail and interchange upgrades by travel time saved, demand, accessibility and total lifetime cost. Publish the business cases before procurement. Pair station improvements with safe crossings, secure cycle parking and dependable feeder services.'],
  ]},
  { id:'services', number:'04', name:'Services that answer', title:'A public service should have a clear next step.', intro:'Strong schools and reachable care are part of a successful capital. Residents should be able to see what is funded, what is working and who can put a failure right.', items:[
    ['Care that measures the whole wait', 'Seek funded district plans for same-day urgent primary care and routine appointments within seven days, phased with verified staffing. Count people unable to book and report subsequent treatment waits. Where a clinically defined treatment guarantee is missed, the commissioner must arrange suitable alternative care at no extra charge.'],
    ['Strong foundations, useful qualifications', 'Back clear reading, writing and mathematics standards, professional freedom for teachers and technical training connected to real placements. Publish completion and next-destination results with context. Match places to staff, equipment and transparent funding rather than announcing an expansion before it can work.'],
    ['An answer without a digital obstacle course', 'Give routine applications clear deadlines and one responsible contact. Keep telephone and in-person routes available. Share records only for authorized purposes, give people correction rights and guarantee meaningful human review of consequential automated decisions.'],
  ]},
  { id:'accountability', number:'05', name:'Government under law', title:'You should not need an inside contact.', intro:'Jon’s test is simple: fair treatment, public reasons and a usable way to challenge power. An ambitious government still has limits.', items:[
    ['A dashboard with the difficult numbers too', 'Seek quarterly public reporting on transit reliability, energy-project costs, permit times and neighborhood service requests. Show the baseline, responsible agency, next milestone and explanation for any delay. Publish usable data, not just favorable headlines.'],
    ['Rights that do not depend on agreement', 'Defend expression, equal treatment and lawful ownership, including the right to appeal an adverse decision. Hold open constituency sessions and publish anonymized themes and follow-up actions. Keep private casework private; asking for help must not turn someone’s circumstances into campaign publicity.'],
    ['Use the MP’s role honestly', 'An MP cannot personally run transit or grant local planning permission. Jon will pursue agreements, scrutinize budgets and report his votes. Recurring promises need recurring funding. National gross debt is 68% of GDP in 2068; 65% by 2072 is a proposed goal under normal conditions, not money already available to spend.'],
  ]},
];
const photo = (name:string) => `/images/montiablo/${name}.jpg`;

export default function Montiablo() {
 return <div className="jon68">
  <a className="campaign-skip" href="#main">Skip to content</a>
  <PlatformHeader/><nav className="candidate-localbar" aria-label="Montiablo campaign"><a href="#plan">The plan</a><a href="#jon">Meet Jon</a><a href="#join">Get involved</a></nav>
  <main id="main">
   <section className="jon-hero">
    <div className="jon-masthead jon-width"><p className="campaign-label">Jon Fraser · People’s Party · Montiablo 2068</p><h1>A capital that<br/>gives you <em>more.</em></h1><div className="jon-hero-note"><p>Room to live.<br/>Freedom to work.<br/>Government that answers.</p><a className="jon-link" href="#plan">Read the city agenda <span aria-hidden="true">↓</span></a></div></div>
    <div className="jon-hero-photo"><img src={photo('jon-outdoors')} alt="Jon Fraser, represented by Michael Vincent Lawler, outdoors" fetchPriority="high"/><div className="jon-name"><span>FOR MONTIABLO</span><strong>Jon Fraser.</strong><a href="#jon">Meet your candidate <span aria-hidden="true">↗</span></a></div></div>
   </section>
   <nav className="jon-chapter-nav jon-width" aria-label="Explore the plan">{chapters.map(c=><a key={c.id} href={`#${c.id}`}><span>{c.number}</span>{c.name}<span aria-hidden="true">↓</span></a>)}</nav>
   <section className="jon-intro jon-width"><p className="campaign-label">The capital belongs to the people who make it work</p><div><h2>Make city life<br/><em>add up.</em></h2><p>A home within reach of work. A journey that makes its connection. A business that can get a straight answer. A successful capital is built from the ordinary things people need to go right.<br/><br/>Jon’s agenda starts with homes and enterprise, connects the region and asks the same demanding questions of every public service: who is responsible, what is the standard and where does the money come from?</p></div></section>
   <section className="jon-transit"><div className="jon-transit-picture"><img src={photo('transit')} alt="A modern tram traveling through a walkable city neighborhood" loading="lazy"/><span>LESS TIME CHANGING TICKETS. MORE TIME LIVING.</span></div><div className="jon-transit-copy"><p className="campaign-label">The connected capital</p><h2>Your life doesn’t<br/>stop at a border.<br/><em>Your ticket shouldn’t either.</em></h2><p>Bus to rail. Ferry to metro. A trip across the region should feel like one journey, with one fare system and connections you can count on.</p><div className="jon-route" aria-label="Proposed CATA integration connects Oplana, Montiablo and Reno"><span>Oplana</span><strong>Montiablo</strong><span>Reno</span></div><small>ONE CONNECTED REGION · CATA PROPOSAL</small><a className="jon-link" href="#connections">See the transport commitments <span aria-hidden="true">↗</span></a></div></section>
   <section className="jon-life jon-width"><div className="jon-life-heading"><p className="campaign-label">Make room for what comes next</p><h2>A place to begin.<br/><em>A reason to stay.</em></h2></div><div className="jon-life-grid"><article><img src={photo('homes')} alt="Apartments with balconies and a pedestrian walkway" loading="lazy"/><p className="campaign-label">A home, not a distant possibility</p><h3>Stay close to the life<br/>you have built.</h3><p>More housing near frequent transit, with the services to match. Dependable renting and ownership support that adds homes, not just another bidder.</p><a className="jon-link" href="#homes">Room to put down roots <span aria-hidden="true">↗</span></a></article><article><img src={photo('enterprise')} alt="Two café staff working behind the counter" loading="lazy"/><p className="campaign-label">Back the people who take a chance</p><h3>Your first customer.<br/>Not your fifth form.</h3><p>A clear route through permits, a person who owns the case and fees you can understand. Spend your energy opening the doors, not chasing an answer.</p><a className="jon-link" href="#opportunity">A capital open for business <span aria-hidden="true">↗</span></a></article></div></section>

   <section className="jon-project jon-width" id="power" aria-labelledby="jon-project-title"><div className="jon-project-summary"><p className="campaign-label">Public decision file / New Homerville</p><h2 id="jon-project-title">Ambition.<br/><em>With conditions.</em></h2><p className="jon-project-capacity"><strong>7,000 <span>MW</span></strong><small>PROPOSED CAPACITY · NOT POWER ALREADY DELIVERED</small></p><p>Jon backs the proposed New Homerville project subject to independent safety, financing and cost reviews. Support is not a blank check.</p></div><div className="jon-project-gates"><p className="campaign-label">Three tests before the next commitment</p><ol><li><span>01</span><div><h3>Prove the case.</h3><p>Compare alternatives on cost, safety and reliability. Publish a bill-impact assessment covering generation, grid upgrades and financing.</p></div></li><li><span>02</span><div><h3>Disclose the exposure.</h3><p>Show guarantees, contract changes and taxpayer risks. Publish construction milestones and the cost of maintaining the asset.</p></div></li><li><span>03</span><div><h3>Release funds in stages.</h3><p>Tie decisions to independently verified progress. Bring material overruns back for scrutiny before making further commitments.</p></div></li></ol><Link className="jon-link" href="/platform/infrastructure">The Alliance’s investment rules <span aria-hidden="true">↗</span></Link></div></section>
   <section className="jon-night"><div><p className="campaign-label">A city is more than its working day</p><h2>Keep the lights on.<br/><em>Keep the city alive.</em></h2><p>The small stage. The late café. The place that gave a new artist a first chance. Culture is part of the capital’s economy and part of what makes it home.</p><p>Jon backs simpler venue licensing, fair rules for neighbors and transport that considers the journey home after the last encore.</p><a className="jon-link" href="#opportunity">Space for the capital’s culture <span aria-hidden="true">↗</span></a></div><img src={photo('culture')} alt="Concertgoers enjoying live music under warm stage lighting" loading="lazy"/></section>
   <section className="jon-plan jon-width" id="plan"><div className="jon-plan-head"><div><p className="campaign-label">The Montiablo agenda · 2068</p><h2>The detail behind<br/><em>the difference.</em></h2></div><p>Five priorities. A public test for each.<br/>These are proposals Jon will pursue with the authorities responsible for delivery.</p></div><div className="jon-policy-layout"><aside aria-label="Policy chapters">{chapters.map(c=><a key={c.id} href={`#${c.id}`}><span>{c.number}</span>{c.name}</a>)}<Link href="/manifesto/caprica-freedom-to-build-2068.pdf" target="_blank" rel="noreferrer">Alliance manifesto <span aria-hidden="true">↗</span></Link></aside><div>{chapters.map(c=><article id={c.id} className="jon-policy" key={c.id}><p className="campaign-label">{c.number} / {c.name}</p><h3>{c.title}</h3><p>{c.intro}</p>{c.items.map(([title,text],index)=><details key={title} open={index === 0}><summary>{title}<span aria-hidden="true">↓</span></summary><p>{text}</p></details>)}</article>)}</div></div></section>
   <section className="jon-capital"><img src={photo('capital-connections')} alt="An illuminated bridge connecting communities across a broad river" loading="lazy"/><div><p className="campaign-label">Local purpose. National ambition.</p><h2>A stronger capital.<br/><em>A more confident Caprica.</em></h2><p>The Alliance’s freedom to build should be felt here: in the home you can find, the business you can start and the journey you can trust. Jon brings Montiablo’s priorities to that shared national program.</p><Link className="jon-link" href="/platform/economy/">Explore the Alliance’s economic plan <span aria-hidden="true">↗</span></Link></div></section>
   <section className="jon-about jon-width" id="jon"><div><p className="campaign-label">Meet Jon Fraser</p><h2>The law matters.<br/>So does<br/><em>the follow-through.</em></h2><p className="jon-signature">Jon Fraser<span>PEOPLE’S PARTY · MONTIABLO</span></p></div><div><p className="jon-lead">Jon has served as Attorney General of Montiablo for eight years. He is now standing for a capital that works as one connected region, and for public decisions people can actually follow.</p><p>His campaign puts practical reform ahead of another list of disconnected projects. Integrate CATA. Scrutinize New Homerville. Make it easier to find a home, open a business or keep a cultural venue working. Show residents who is responsible and what happens next.</p><p>As the People’s Party candidate within the Liberal-Conservative Alliance, he will argue for Montiablo at the national table while working with neighboring representatives on the issues no region can solve alone.</p><div className="jon-role-note"><strong>The responsibility is clear.</strong><p>Jon would convene, legislate and scrutinize. Transit operators, local planning bodies and service commissioners would still deliver. Residents should know which institution must answer each question.</p></div><Link className="jon-link" href="/team/#jon">Meet the wider Alliance team <span aria-hidden="true">↗</span></Link></div></section>
   <section className="jon-join" id="join"><div className="jon-width"><p className="campaign-label">Bring your city into the conversation</p><h2>What would make<br/>Montiablo work<br/><em>better for you?</em></h2><div><p>A connection that never works? A business you want to open? A neighborhood that deserves a hearing?<br/><br/>Bring it to the Alliance’s Montiablo forum. The next chapter starts with the people who live here.</p><Link className="jon-button" href="/events/#caprica-we-can-build">Find the Montiablo forum <span aria-hidden="true">↗</span></Link><CandidateActions name="Jon Fraser" region="Montiablo" commitments={["More homes near frequent transit and dependable renting.", "Clear business permits, open contracts and timely public payments.", "CATA fare integration with Oplana and Reno.", "Independent safety, financing and cost tests for New Homerville.", "Reachable services and public decisions people can challenge."]}/></div></div></section>
  </main>
  <footer className="jon-footer jon-width"><Link className="jon-brand" href="/jon-fraser/"><img src="/images/pp-logo.png" alt="People’s Party" width="44" height="44"/><span>JON FRASER<small>FOR MONTIABLO · 2068</small></span></Link><Link href="/">The Alliance <span aria-hidden="true">↗</span></Link><a href="#main">Back to top ↑</a></footer>
  <details className="jon-credits jon-width"><summary>Photography &amp; credits</summary><p>Michael Vincent Lawler is the face claim for fictional candidate Jon Fraser. Portrait: <a href="https://www.lawlerforcongress.com/">Mike Lawler campaign</a>. Bridge: <a href="https://lawler.house.gov/">Office of Congressman Mike Lawler</a>. Illustrative city photography, not documentary images of Caprica: <a href="https://unsplash.com/photos/F_hXLZRPfYQ">Marek Lumi</a>, <a href="https://unsplash.com/photos/VxVldSjtmQI">Timon Reinhard</a>, <a href="https://unsplash.com/photos/o0goy2sHsCA">Yan Kolesnyk</a> and <a href="https://unsplash.com/photos/d8clU5pcFJQ">Rafael Garcin</a>, via Unsplash.</p></details>
 </div>;
}
