import Link from 'next/link';
import type { Metadata } from 'next';
import { PlatformHeader } from '../platform/PlatformChrome';
import CandidateActions from '../components/CandidateActions';
import './reno-review.css';

export const metadata: Metadata = {
 title: 'Roberto Libero for Reno | A good life. On solid ground. | 2068',
 description: 'Roberto Libero’s 2068 plan for Reno: accountable government, connected neighborhoods and the freedom to build a good life. Moderate Reform, within the Alliance.',
 icons: { icon: '/images/mr-logo.png', shortcut: '/images/mr-logo.png' },
};
const photo = (name:string) => `/images/reno/${name}.jpg`;
const Arrow = () => <span aria-hidden="true">↗</span>;

export default function Reno(){return <div className="reno68">
 <a className="campaign-skip" href="#main">Skip to content</a>
 <PlatformHeader/><nav className="candidate-localbar" aria-label="Reno campaign"><a href="#plan">The Reno plan</a><a href="#roberto">Meet Roberto</a><a href="#join">Take part</a></nav>
 <main id="main">
  <section className="reno-hero reno-width">
   <div className="reno-hero-copy"><p className="campaign-label">Roberto Libero · Moderate Reform</p><h1>A good life.<br/>On <em>solid<br/>ground.</em></h1><p className="reno-deck">Room for your ambitions.<br/>Respect for the life you have built.</p><a className="reno-button" href="#plan">Read the Reno prospectus <Arrow/></a><div className="reno-hero-signoff"><span>YOUR HOME. YOUR TIME. YOUR SAY.</span><span>RENO / 2068</span></div></div>
   <figure className="reno-portrait"><a href="https://commons.wikimedia.org/wiki/File:Romeu_Zema_2025_(cropped).jpg" target="_blank" rel="noreferrer" title="Portrait: Paulo Guereta / Governo do Estado de SP, CC BY 4.0. Cropped source photograph. Source and license." aria-label="Portrait photograph source and license"><img src={photo('roberto-libero')} alt="Roberto Libero, represented by Romeu Zema, wearing glasses and a dark jacket" width="1161" height="1550" fetchPriority="high"/></a><figcaption><span>ROBERTO<br/><strong>LIBERO</strong></span><a href="#roberto">Meet your candidate <Arrow/></a></figcaption></figure>
  </section>
  <section className="reno-opening reno-width" id="plan"><p className="campaign-label">The Reno plan</p><div><h2>Keep what makes<br/>life good.<br/><em>Make room for more.</em></h2><div className="reno-opening-text"><p>Saturday at the shops. Dinner with friends. The quiet street you turn into at the end of a long day. Reno offers a life people work hard to build, and good government should help them keep it.</p><p>That means a dependable journey to work, neighborhoods cared for properly, and room for the next generation to put down roots. It also means a government that respects your money, your rights and your right to an answer.</p><p>Roberto Libero brings a constitutional scholar’s discipline to those everyday expectations. His starting point is simple: public power must serve the people who live with its decisions.</p></div></div></section>
  <nav className="reno-index reno-width" aria-label="Explore Roberto’s priorities"><a href="#your-time"><span>01 / YOUR TIME</span>A journey that works <Arrow/></a><a href="#your-home"><span>02 / YOUR HOME</span>Room to belong <Arrow/></a><a href="#your-economy"><span>03 / YOUR ECONOMY</span>Keep Reno thriving <Arrow/></a><a href="#your-services"><span>04 / YOUR CONFIDENCE</span>Care. Safety. Peace of mind. <Arrow/></a><a href="#your-government"><span>05 / YOUR GOVERNMENT</span>Power with limits <Arrow/></a></nav>

  <section className="reno-journey" id="your-time"><div className="reno-journey-photo"><img src={photo('commute')} alt="Passengers boarding a modern train at a bright, accessible platform" loading="lazy"/><p>THE JOURNEY HOME IS PART OF YOUR QUALITY OF LIFE.</p></div><div className="reno-journey-copy"><p className="campaign-label">01 / Your time</p><h2>Home is the point.<br/><em>Not the commute.</em></h2><p className="reno-lead">Reno and Montiablo share a working day. Their transport systems should act like it.</p><p>Roberto will work with the Alliance’s neighboring representatives for a common CATA fare system across bus, tram, metro, ferry and regional rail. The proposed daily cap would work with the Alliance’s weekly cap across participating networks. Coordinated transfers and cash-accessible payment would simplify a regional journey without forcing everyone onto an app.</p><p>Start with the connections people actually miss. Publish reliability by route, coordinate first and last services for shift workers, and make accessibility part of operating contracts. Fund improvements through a published agreement between the responsible authorities, with clear costs and responsibilities.</p><div className="reno-policy-links"><Link className="reno-link" href="/jon-fraser/#connections">A shared commitment with Jon Fraser <Arrow/></Link><Link className="reno-link" href="/platform/infrastructure/">The national infrastructure plan <Arrow/></Link></div></div></section>

  <section className="reno-homes reno-width" id="your-home"><div className="reno-homes-copy"><p className="campaign-label">02 / Your home</p><h2>You shouldn’t have<br/>to leave Reno<br/><em>to start your life.</em></h2><p className="reno-lead">A first place of your own. A little more space. Somewhere smaller, near the people you love.</p><p>Reno’s appeal should not become a closed door. Roberto backs more housing choices on suitable sites near frequent transit and established centers, including smaller homes for people who want to downsize and apartments for those taking their first step.</p><p>Growth should come with a plan for school places, water, safe crossings and recreation, agreed before major development goes ahead. Publish the infrastructure funding and construction sequence so existing neighbors can see what will change and new residents are not left waiting for basic services.</p><p>Protect established green spaces and give residents a meaningful hearing. Apply the Alliance’s decision clock: 120 days for complete growth-zone applications, or 60 days for compliant infill using approved designs, with safety and environmental safeguards intact. A decision deadline is not automatic permission. It is an end to leaving everyone in limbo.</p><Link className="reno-link" href="/platform/housing/">Reno’s part in the Alliance housing plan <Arrow/></Link></div><figure><img src={photo('homes')} alt="A leafy residential street with homes, sidewalks and space for cycling" loading="lazy"/><figcaption>A place to stay, through every stage of life.</figcaption></figure></section>

  <section className="reno-economy" id="your-economy"><div className="reno-width"><div className="reno-economy-head"><p className="campaign-label">03 / Your economy</p><h2>The places you love.<br/><em>The people who make them work.</em></h2><p>Reno’s shops, restaurants and leisure venues are more than a way to spend a weekend. They are employers, first businesses and the places a neighborhood comes together.</p></div><img className="reno-cafe" src={photo('cafe')} alt="Friends talking over lunch at an outdoor neighborhood café" loading="lazy"/><div className="reno-economy-copy"><div className="reno-economy-margin"><h3>Let the next good<br/>idea open its doors.</h3><Link className="reno-link" href="/platform/economy/">Enterprise, without favoritism <Arrow/></Link></div><div className="reno-economy-prose"><p>Roberto will press for a single application route for routine business and premises permits, with one named officer, clear fees and a published decision clock. Inspections should reflect actual risk. Delays should trigger escalation, not automatic permission to open an unsafe venue.</p><p>Make it easier to bring empty shops back into use through temporary-use licenses with clear safety and noise conditions. Coordinate deliveries, access and evening transport with local businesses and residents. A thriving center needs customers who can reach it and staff who can get home.</p><p>Use the Alliance’s equipment-expensing proposals to help firms invest, and its prompt-payment standard to stop small suppliers financing government’s delays. Support should follow published rules, not a relationship with a minister. Compete for the customer; do not compete for political favors.</p></div></div></div></section>

  <section className="reno-standard" id="your-services" aria-labelledby="reno-standard-title"><div className="reno-width"><div className="reno-standard-heading"><p className="campaign-label">04 / Your confidence · The Reno standard</p><h2 id="reno-standard-title">A good place to live.<br/><em>Even when plans change.</em></h2><p>Quality of life is also the appointment you can get, the school that teaches well and the public service that does not send you back to the beginning.</p></div><div className="reno-standard-body"><article className="reno-service-story"><h3>Care that gives you<br/>a clear next step.</h3><p>Roberto will seek a funded district access plan for Reno, with staffing and referral arrangements published before a guarantee begins. Count the people unable to book, not just the people already on a waiting list. When an elective service misses a clinically defined maximum wait, the national plan requires suitable alternative care at no extra charge.</p><Link className="reno-link" href="/platform/healthcare/">Read the healthcare guarantee <Arrow/></Link><h3>A strong start.<br/>A worthwhile next step.</h3><p>Back protected reading, writing and mathematics, with professional freedom for teachers and clear information for families. Bring colleges and local employers together around accredited, paid training in care, construction and Reno’s service economy. Publish completion and employment outcomes so a qualification means more than a prospectus.</p><Link className="reno-link" href="/platform/education/">The education and skills plan <Arrow/></Link></article><aside className="reno-access-note" aria-label="The Alliance primary care access proposal"><p className="campaign-label">The national access proposal</p><dl><div><dt>Urgent primary care</dt><dd>Same day.</dd></div><div><dt>Routine appointments</dt><dd>Within<br/><em>seven days.</em></dd></div></dl><p>Phased with verified staffing and funded capacity. These are proposed standards, not a claim about current waiting times.</p><span>THE TEST: CAN PEOPLE ACTUALLY REACH CARE?</span></aside></div></div></section>

  <section className="reno-confidence reno-width" id="your-confidence"><figure><img src={photo('park')} alt="A couple walking along a sunlit path beneath mature trees in a neighborhood park" loading="lazy"/><figcaption>Peace of mind should extend beyond your front door.</figcaption></figure><div><p className="campaign-label">The Reno standard · In the neighborhood</p><h2>Feel safe.<br/>Stay free.<br/><em>Expect both.</em></h2><p className="reno-lead">A well-kept park. A safe trip home. Someone who takes a report seriously.</p><p>Roberto supports visible neighborhood policing focused on repeat theft, harassment and the places residents identify as unsafe. Police should publish response times and case follow-up standards, alongside an independent route for complaints. Prevention matters too: repair failed lighting, improve crossings and design public spaces with clear sightlines.</p><p>Security is not a blank check for surveillance. New monitoring systems should need an evidence-based case, narrow purposes, limits on data retention and independent oversight. The same law must protect the shopper, the business owner and the person stopped on the street.</p><p>For local services, residents deserve one case reference and a clear escalation route when a repair goes unanswered. Publish maintenance backlogs and response times, including the difficult figures. A prosperous region still has to get the basics right.</p><a className="reno-link" href="#your-government">The constitutional principle behind it <Arrow/></a></div></section>

  <section className="reno-government" id="your-government"><div className="reno-width"><p className="campaign-label">05 / Your government</p><h2>The rules should<br/>bind the people<br/><em>who make them.</em></h2><div className="reno-government-intro"><span className="reno-principle">A CONSTITUTIONAL PRINCIPLE.<br/>AN EVERYDAY GUARANTEE.</span><p>When ministers can rewrite the rules without scrutiny, families and businesses cannot plan with confidence. Libero’s defense of Parliament is a defense of your right to know, to question and to be treated fairly.</p></div><div className="reno-government-columns"><article><h3>No permanent<br/>emergency powers.</h3><p>Require a clear legal basis, a defined expiry date and parliamentary approval for extending emergency measures. Major changes to citizens’ rights belong in legislation, with time for scrutiny, rather than being smuggled through executive orders. Preserve independent courts and access to judicial review.</p></article><article><h3>Your money.<br/>A public account.</h3><p>Publish the costs, funding and long-term obligations behind major projects before commitments are made. Disclose contract changes and public guarantees, protect independent audit and require ministers to answer substantive committee findings. An impressive announcement is not a substitute for a sound business case.</p></article><article><h3>Conviction without<br/>the closed mind.</h3><p>Review programs against evidence of results. Keep what works, repair what does not and explain the tradeoffs. Avoid unfunded promises of tax cuts or spending increases. Constitutional restraint and financial discipline should apply to Roberto’s own side just as firmly as to its opponents.</p></article></div><Link className="reno-link" href="/platform/civil-liberties/">Read the Alliance’s civil liberties commitments <Arrow/></Link></div></section>

  <section className="reno-about reno-width" id="roberto"><div className="reno-about-title"><p className="campaign-label">Meet Roberto Libero</p><h2>A serious mind.<br/><em>An independent<br/>judgment.</em></h2><div className="reno-monogram" aria-hidden="true">RL<span>RENO · 2068</span></div></div><div className="reno-about-copy"><p className="reno-lead">The son of a defense attorney, Roberto took a more academic path. As a respected professor of constitutional law, he made institutional balance and the limits of executive authority central to his work.</p><p>His move into politics grew from frustration with the erosion of parliamentary sovereignty. He believed that decisions affecting the whole country were slipping beyond the scrutiny of its elected representatives, and that defending those institutions required more than writing about them.</p><p>Within his party, he became known as a disciplined, technically minded figure. He is distinctly conservative, but practical about how government works: examine the evidence, understand the legal powers, test the cost and listen to people who disagree.</p><p>That combination matters in Reno. A community built around homes, enterprise and a high quality of life needs confidence in the rules, careful stewardship of public money and a representative who does the reading before making the promise.</p><p>As Moderate Reform’s candidate within the Liberal-Conservative Alliance, Roberto will bring Reno’s priorities to the national program. He will work across regional boundaries where cooperation helps, and scrutinize his own government where scrutiny is needed.</p><p className="reno-role">An MP’s job is to legislate, scrutinize and represent. Roberto will seek agreements with the agencies responsible for transport, policing and local services, and publish an account of the votes and decisions he can actually influence.</p></div></section>

  <section className="reno-representation reno-width" aria-labelledby="reno-representation-title"><p className="campaign-label">Representation, with a record</p><div><h2 id="reno-representation-title">The work should<br/><em>be open to question.</em></h2><div><p>Roberto will publish a quarterly constituency account: the votes he cast, the agreements he is seeking and the agency responsible when delivery stalls. Residents should see both the progress and the unresolved questions.</p><p>Homes, enterprise, infrastructure and services all depend on the same foundation: lawful authority and honest public finances. Reno’s case will be made within the Alliance’s national framework, not through a separate set of unfunded promises.</p><Link className="reno-link" href="/2068/#priorities">The five priorities working together <Arrow/></Link></div></div></section>

  <section className="reno-join" id="join"><div className="reno-width"><div><p className="campaign-label">A good life. On solid ground.</p><h2>Let’s talk<br/><em>about your Reno.</em></h2><p>Your next home. Your daily journey.<br/>The place you want your children to grow up.<br/>Bring your questions to the conversation.</p><CandidateActions name="Roberto Libero" region="Reno" commitments={['Seek a common CATA fare system and reliable connections with neighboring Montiablo, backed by published funding agreements.','Back homes near transport with services planned in advance and the Alliance’s 120-day and 60-day planning decision standards.','Simplify business permits, support equipment investment and keep public procurement open to fair competition.','Seek funded care-access plans and accredited training, with staffing verified before healthcare guarantees begin.','Defend parliamentary sovereignty, independent courts and open public accounts; publish quarterly votes, progress and unresolved questions.']}/></div><div className="reno-invitation"><p className="campaign-label">The Alliance in Reno</p><h3>Homes<br/>Within Reach.</h3><p>October 10, 2068 · 18:30<br/>Riverside Works · Reno</p><Link className="reno-button" href="/events/#homes-within-reach">Event details &amp; calendar <Arrow/></Link><Link className="reno-link" href="/manifesto/caprica-freedom-to-build-2068.pdf" target="_blank" rel="noreferrer">Read the 2068 Alliance manifesto · PDF <Arrow/></Link></div></div></section>
 </main>
 <footer className="reno-footer reno-width"><Link className="reno-brand" href="/roberto-libero/"><img src="/images/mr-logo.png" alt="Moderate Reform" width="54" height="32"/><span>LIBERO<small>FOR RENO · 2068</small></span></Link><p>Moderate Reform.<br/>Part of the Liberal-Conservative Alliance.</p><Link href="/team/#libero">The Alliance team <Arrow/></Link><a href="#main">Back to top ↑</a></footer>
</div>;}
