import Link from "next/link";
import { PlatformHeader } from "../platform/PlatformChrome";

const plans = [
  { id: "water", label: "Water & public services", title: "Turn on the tap. Trust what comes out.", text: "Clean water is the first test of a government that works. A family should know its supply is safe, and a farmer should know who will fix a failing pipe.", details: [
    ["Repair the worst problems first", "Seek a ten year regional renewal agreement, starting with an independently assessed list of failing pipes and treatment systems. Prioritize contamination risks, schools, clinics and communities facing repeated interruptions. Publish costs and the authority responsible before work begins."],
    ["Make the results easy to find", "Publish water tests, repair schedules and interruption notices by district, online and through local service points. Give residents a named contact and a clear route to escalate an unresolved problem. National investment should come with visible local responsibility."],
    ["Protect the source as well as the supply", "Work with farmers on soil health, efficient irrigation and runoff control. Stewardship payments should buy measurable improvements in water quality and habitat, with practical advice and transparent results. Protect productive land while restoring rivers and catchments."]
  ]},
  { id: "farms", label: "Farms & local enterprise", title: "Grow it here. Keep more of its value here.", text: "Ambrosia produces the food. More of the processing, skilled work and business income should stay in the communities that grow it.", details: [
    ["Back the next investment", "Connect farms and local firms to the Alliance’s proposed immediate expensing of qualifying equipment. Help businesses compare machinery, irrigation and storage investments on their merits. Support must be open to family firms, with clear eligibility and published costs."],
    ["Bring processing closer to the farm", "Use competitive regional agreements to address missing cold storage, food processing and freight connections. Require credible demand, private investment and an independent business case before committing public funds. Measure the additional value retained locally."],
    ["Open a route to new customers", "Bring national export certification, logistics and trade finance advice to Ambrosian producers through a regional service. Connect small exporters to the Alliance’s single customs window and Columbian market agreements, with clear fees and limits on public exposure."]
  ]},
  { id: "connections", label: "Roads & connections", title: "The last few miles matter.", text: "A new export agreement means little if a truck cannot reach the farm. Opportunity depends on the everyday connections between our villages, towns and western ports.", details: [
    ["Repair the routes we rely on", "Publish a condition survey of roads, bridges and freight bottlenecks, then agree a funded maintenance schedule with regional authorities. Put safety, school access and reliable journeys to market first. Every major proposal must account for its running costs."],
    ["Make a reliable connection the standard", "Map broadband gaps and tender support for areas the market cannot serve alone. Contracts should specify usable speeds, reliability and remedies when service falls short. Keep assisted and telephone access to essential public services."],
    ["Make services reachable", "Work with operators on practical links between Auburne, Garrison, Strawberry, Meridian and nearby villages. Coordinate timetables around work, study and health appointments. Bring participating services into the national fare cap as agreements are reached."]
  ]},
  { id: "future", label: "Homes, skills & community", title: "Your next chapter can start at home.", text: "Leaving Ambrosia should be a choice. Staying should offer a real chance at a home, a useful qualification and work with a future.", details: [
    ["Homes with services from the start", "Seek growth agreements for Strawberry and Meridian that join housing to water, school places, transport and jobs. Support well designed infill in existing towns. Ambrosia’s contribution to the national housing goal must protect flood safety and productive farmland."],
    ["A qualification that leads somewhere", "Bring employers and technical colleges together around agriculture, food technology, engineering, health and tourism. Share apprenticeship administration so smaller businesses can take part. Under the national proposal, eligible people under 25 receive an offer within 90 days after four months outside work or education."],
    ["A good place to grow older, too", "Support local access to primary care, accessible transport and the national funded respite offer for unpaid caregivers. Develop tourism around Mount Ambrosia within habitat and water limits, creating work that helps sustain services throughout the year."]
  ]},
];

export default function AmbrosiaCampaign() {
  return <div className="amb68-root">
    <a className="campaign-skip" href="#ambrosia-main">Skip to content</a>
    <PlatformHeader/><nav className="candidate-localbar" aria-label="Ambrosia campaign"><a href="#plan">Our plan</a><a href="#about">Meet Alistair</a><a href="#take-part">Get involved</a></nav>
    <main id="ambrosia-main">
      <section className="amb68-hero"><div className="amb68-hero-copy"><p className="campaign-label">People’s Party · Ambrosia · 2068</p><h1>A future<br/>you can<br/><em>build here.</em></h1><p>Alistair Foulke-McKeon for Ambrosia.<br/>Strong farms. Dependable services. Room to make a life.</p><a className="campaign-text-link" href="#plan">Our plan for Ambrosia <span aria-hidden="true">↓</span></a></div><figure><img src="/images/alistair-hero-hd.jpg" alt="Alistair Foulke-McKeon" fetchPriority="high"/><figcaption>ALISTAIR FOULKE-MCKEON / PEOPLE’S PARTY</figcaption></figure></section>
      <section className="amb68-opening campaign-width"><p className="campaign-label">The choice in 2068</p><div><h2>You should not have to leave the place you love <em>to get ahead.</em></h2><div className="amb68-prose"><p>Ambrosia feeds Caprica. Its farms, small businesses and close communities are a national strength. Yet a broken water main, an unreliable road or a lack of nearby training can still put an ordinary ambition out of reach.</p><p>Caprica’s gross public debt now stands at 68% of GDP. The People’s Party believes stronger national finances must support opportunity people can see in their own towns. That is the case Alistair will make for Ambrosia in the next Parliament.</p><p>Clean water at home. More value from what we grow. A decent connection to work and care. A future here, for every generation.</p></div></div></section>
      <section className="amb68-land"><figure><img src="/images/events/ambrosia-fields.jpg" alt="A rural road connects farms, grain storage and fields" loading="lazy"/></figure><div><p className="campaign-label">Rooted in Ambrosia</p><h2>Our land.<br/>Our livelihoods.<br/><em>Our next chapter.</em></h2><p>With 80% of its landmass rural, Ambrosia needs a plan that understands distance, farming seasons and small employers. From Auburne and Garrison to growing Strawberry and Meridian, growth should strengthen the communities already here.</p><a className="campaign-text-link" href="#farms">More value from our farms <span aria-hidden="true">↓</span></a></div></section>
      <section className="amb68-plan campaign-width" id="plan"><div className="amb68-plan-heading"><p className="campaign-label">The Ambrosia plan / 2068 to 2072</p><h2>Four priorities.<br/><em>One place we call home.</em></h2><p>Local proposals connected to the Alliance’s national program. Open each commitment for the practical steps, safeguards and funding approach.</p></div><nav className="amb68-plan-index" aria-label="Policy topics">{plans.map(p=><a key={p.id} href={`#${p.id}`}>{p.label}<span aria-hidden="true">↓</span></a>)}</nav>{plans.map((p,i)=><article className="amb68-policy" id={p.id} key={p.id}><div className="amb68-policy-intro"><p className="campaign-label">0{i+1} / {p.label}</p><h3>{p.title}</h3><p>{p.text}</p></div><div className="belief-accordions">{p.details.map(([heading,body])=><details key={heading}><summary>{heading}<span aria-hidden="true">+</span></summary><p>{body}</p></details>)}</div></article>)}</section>
      <section className="amb68-pledge"><div className="campaign-width"><p className="campaign-label">How Alistair will represent you</p><h2>Know who to call.<br/><em>See what gets done.</em></h2><div className="amb68-three"><article><h3>Regular community office hours.</h3><p>Publish a rotation of constituent meetings across our towns, with telephone appointments for people who cannot travel. Tell residents how to bring a case and when to expect a response.</p></article><article><h3>A visible record of progress.</h3><p>Report each quarter on the regional commitments, the decisions still needed and any delays. Explain which level of government holds the responsibility and the funding.</p></article><article><h3>Honest funding.</h3><p>Put costs, maintenance and delivery capacity alongside every major proposal. Ambrosia’s plans must meet the same independent appraisal and fiscal rules as the national manifesto.</p></article></div></div></section>
      <section className="amb68-about campaign-width" id="about"><figure><img src="/images/alistair-podium-hd.jpg" alt="Alistair speaking at a lectern" loading="lazy"/></figure><div><p className="campaign-label">Meet Alistair</p><h2>Ambrosia shaped him.<br/><em>Service brought him here.</em></h2><p>Alistair grew up on the Foulke family estate in rural Ambrosia. He is the grandson of former President and Prime Minister Darjeeling Foulke, but the experience he brings to this campaign is also local: the rhythms of farm country and the long work of representing a community.</p><p>Born at St. Joseph’s Hospital in Auburne, Montiablo, he studied international relations at the University of Auburne. A pitcher and right fielder at school, he helped his baseball team reach the regional summer tournament quarterfinals and played a year at college before focusing on his degree.</p><p>He went on to work at the Foulke Institute and became active in the National Party, later joining Moderate Reform. He married Elizabeth McKeon in 2034, taking the surname Foulke-McKeon, and was first elected on the Ambrosia Country Liberal Party list in 2040.</p><p>In 2068, Alistair is the People’s Party candidate for Ambrosia within the Liberal-Conservative Alliance. He brings deep local experience to a shared national program, and a clear commitment to making rural voices count.</p><Link className="campaign-text-link" href="/team/#alistair">Meet the Alliance team <span aria-hidden="true">↗</span></Link></div></section>
      <section className="amb68-alliance campaign-width"><p className="campaign-label">A local voice. A shared purpose.</p><div><h2>Freedom to build.<br/><em>Confidence in tomorrow.</em></h2><p>The Alliance brings Moderate Reform, the People’s Party and Avenir Caprica together. Alistair’s regional plan connects to the same national commitments on homes, enterprise, care and accountable government.</p><a className="campaign-text-link" href="/manifesto/caprica-freedom-to-build-2068.pdf" target="_blank" rel="noreferrer">Read the 2068 manifesto · PDF <span aria-hidden="true">↗</span></a></div></section>
      <section className="amb68-action" id="take-part"><div className="campaign-width"><p className="campaign-label">Make this campaign yours</p><h2>Ambrosia’s future<br/><em>starts with us.</em></h2><div className="amb68-action-grid"><div><h3>Bring your local knowledge.</h3><p>Come with a question about water, farms or the connections your community needs. Find the campaign’s public conversations and save a date to your calendar.</p><Link className="campaign-text-link" href="/events/#upcoming">Find a campaign event <span aria-hidden="true">↗</span></Link></div><div><h3>Help make the case.</h3><p>Share the Ambrosia plan with a neighbor. Read the national commitments behind it, then bring the questions that matter to you. Event registration details will be announced on the events page.</p><a className="campaign-text-link" href="#plan">Explore the local plan <span aria-hidden="true">↑</span></a><Link className="campaign-text-link" href="/events/#register">Event participation details <span aria-hidden="true">↗</span></Link></div></div></div></section>
    </main><footer className="amb68-footer campaign-width"><Link className="amb68-brand" href="/ambrosia/"><img src="/images/pp-logo.png" alt="People’s Party" width="68" height="42"/><span>ALISTAIR<br/><small>FOR AMBROSIA</small></span></Link><p>People’s Party · Liberal-Conservative Alliance<br/>Ambrosia campaign, 2068</p><Link className="campaign-text-link" href="/">The national campaign <span aria-hidden="true">↗</span></Link></footer>
  </div>;
}
