import Link from 'next/link';
import CandidateActions from '../components/CandidateActions';
import type { Metadata } from 'next';
import { PlatformHeader, PlatformFooter } from '../platform/PlatformChrome';
import './candidate-review.css';

export const metadata: Metadata = { title: 'Pepe Marti Rutte for Cambria | Alliance 2068', description: 'A good life, built here. Pepe’s plan for Cambria’s working coast, mountain communities, industry and next generation.' };

const priorities = [
  { id: 'coast', label: 'Our working coast', title: 'The catch leaves port. More of its value should stay.', intro: 'Fishing is a livelihood, a skill and a way of life. A stronger Ouluksee should open doors for the small boat owner as well as the big exporter.', details: [
    ['A better route from boat to buyer', 'Seek a joint port and fishing harbor plan for Ouluksee: reliable ice, cold storage, landing facilities and access roads. Invite competing operators to provide shared facilities on published terms. Invest where demand supports it, with users contributing to costs and maintenance funded from the start.'],
    ['Give independent crews a fair chance', 'Make landing fees and auction charges easy to compare. Support producer cooperatives and direct sales, with food safety standards that buyers can trust. Simplify catch reporting through one service, with assistance for crews who need it.'],
    ['A living sea for the next generation', 'Base catch limits on independent stock assessments, with fishers involved in the evidence and seasonal planning. Enforce the rules against illegal fishing. Better gear, healthier nursery grounds and less waste are investments in future catches, not obstacles to today’s work.']
  ]},
  { id: 'industry', label: 'Made in Cambria', title: 'A skilled pair of hands deserves a future.', intro: 'Our mines and defense workshops matter to the whole country. We should be building the next generation of expertise here, too.', details: [
    ['Make the next investment possible', 'Connect local firms to the Alliance’s equipment investment reforms. Coordinate planning, power connections and industrial land through a named regional contact, with published decision deadlines. Keep safety and environmental tests clear so firms can plan without buying their way to the front of a queue.'],
    ['An apprenticeship with real work behind it', 'Bring Cambria Technical University and employers together around paid placements in marine engineering, precision manufacturing, electrical trades and mine safety. Share administration between small employers. Publish completion and employment outcomes, and help rural trainees with travel when distance prevents participation.'],
    ['A dependable place in national defense', 'Seek a published procurement pipeline so Cambrian suppliers can prepare for naval, air and support contracts. Break contracts into accessible lots where practical, preserve security screening and compete on quality and lifetime cost. Back civilian applications for engineering expertise rather than making communities depend on one customer.'],
    ['Leave the land safe after the last shift', 'Require mine closure plans, secured restoration funding and independent water monitoring. Publish results residents can understand. Support retraining before a closure, with employers and colleges planning together rather than leaving workers to find out at the gate.']
  ]},
  { id: 'homes', label: 'A home in Cambria', title: 'More homes. Closer to work.', intro: 'An expanding workshop, a busy harbor and a successful college all need homes within reach. Housing belongs in the economic plan, not at the end of it.', details: [
    ['A site with a route to completion', 'Agree suitable sites with Alto and other local authorities, near jobs and existing connections. Set out water, school, clinic and transport capacity before major growth. Use the Alliance’s planning deadlines and open competition for public land, with clear reasons for refusals and an independent appeal.'],
    ['A rental that feels like home', 'Back lasting contracts, portable deposits and enforceable standards for safety, warmth and repairs. Use the national specialist tribunal to settle disputes fairly. Publish local rents, vacancies and construction progress so the response to a shortage is more homes, not another queue.'],
    ['Ownership help that adds supply', 'Connect eligible households to the Alliance’s proposed savings accounts and capped shared ownership for additional new homes. Publish costs, income limits and resale terms first. Public help should make a new home possible without bidding up an existing one.']
  ]},
  { id: 'connections', label: 'Mountain connections', title: 'A mountain road is someone’s way home.', intro: 'In Alto, opportunity may be a bus ride away. In a mountain community, one damaged bridge can put work, college and care out of reach.', details: [
    ['Keep essential routes open', 'Seek a regional audit of bridges, unstable slopes, drainage and emergency access. Prioritize repairs by safety, isolation risk and the journeys people depend on. Publish a maintenance schedule and disruption information before proposing expensive new roads.'],
    ['Bring everyday services within reach', 'Coordinate buses around shifts, college hours and medical appointments. Use competitive service contracts where an essential route cannot pay its way. Pair visiting clinics with dependable referral transport and digital consultations, keeping telephone and in-person access available.'],
    ['A connection that works beyond the map', 'Tender rural broadband support where the market cannot deliver alone. Pay for tested reliability and actual service, not just claimed coverage. Give essential clinics and services backup connections, while keeping a staffed route for people who do not use digital services.']
  ]},
  { id: 'water', label: 'North and south', title: 'Different weather. The same right to a reliable tap.', intro: 'Our greener, wetter north and drier south need different answers. A single promise about “more infrastructure” will not do.', details: [
    ['In the north, work with the water', 'Prioritize drainage, floodplain protection, bridge resilience and slope stability. Restore catchments where evidence shows they reduce flood risk. Keep new homes away from dangerous sites and maintain the infrastructure already protecting communities.'],
    ['In the south, make every drop count', 'Start with leakage surveys and repairs, then assess water reuse and efficient irrigation. Publish drought triggers and fair allocation rules before shortages arrive. Any proposed reservoir or transfer must prove its supply benefit, environmental impact and full cost against alternatives.'],
    ['Keep the decisions in public', 'Publish water quality, interruptions, repair progress and project costs by district. Let residents see who is responsible. Seek national and regional funding agreements with independent appraisal; do not promise a project before its operating costs and water supply are understood.']
  ]},
];

export default function Cambria() {
 return <div className="cam68 p68-root cam-review">
  <a className="campaign-skip" href="#cambria-main">Skip to content</a>
  <PlatformHeader />
  <main id="cambria-main">
   <section className="cam-hero">
    <img src="/images/cambria/coast.jpg" alt="A working harbor beneath green mountain slopes" fetchPriority="high" />
    <div className="cam-hero-copy"><p className="cam-label">Pepe Marti Rutte for Cambria · 2068</p><h1>A good life.<br/><em>Built here.</em></h1><p>From our mountain towns to the working coast.<br/>A future worth making your own.</p><a className="cam-button" href="#plan">My plan for Cambria <span aria-hidden="true">↓</span></a></div>
    <div className="cam-review-nameplate"><span>YOUR VOICE FOR CAMBRIA</span><strong>Pepe<br/>Marti Rutte.</strong><a href="#pepe">Meet your candidate <span aria-hidden="true">↗</span></a></div>
   </section>
   <nav className="cam-local-nav" aria-label="Cambria page"><a href="#pepe">Meet Pepe</a><a href="#place">Our region</a><a href="#plan">The local plan</a><a href="#accountable">My commitment</a></nav>
   <section className="cam-intro cam-width" id="pepe">
    <figure><img src="/images/pepe.png" alt="Pepe Marti Rutte" loading="lazy" width="430" height="430"/><figcaption><strong>Pepe Marti Rutte</strong><span>Candidate for Cambria MP</span></figcaption></figure>
    <div><p className="cam-label">Why I’m standing</p><h2>You should be able<br/>to see a future<br/><em>from your own doorstep.</em></h2><p className="cam-lead">I believe a good life is something people build for themselves. Government should make that possible.</p><p>For me, that means a fishing business able to buy its next boat. An apprentice who can afford the journey to work. A family that can find a home without moving away from everyone they know.</p><p>Cambria already has ambition. You can see it on our quays, in our workshops and in the people learning a trade. I want government to respect that effort: keep the roads open, make the rules fair and give a good idea room to grow.</p><p>I’m asking to represent the whole region. Alto matters. So does the village beyond the last mountain pass.</p><span className="cam-signoff">Pepe</span></div>
   </section>
   <section className="cam-review-place" id="place"><div className="cam-width"><header><p className="cam-label">One region. Different practical needs.</p><h2>The land shapes<br/><em>the plan.</em></h2></header><div className="cam-review-place-grid"><figure><img src="/images/cambria/south.jpg" alt="Dry fields and open mountain country beneath a wide blue sky" loading="lazy"/><figcaption>FROM THE MOUNTAIN PASS TO THE WORKING COAST.</figcaption></figure><div className="cam-review-place-rows"><article><span>01 / THE WETTER NORTH</span><h3>Keep life moving<br/>when the rain comes.</h3><p>Drainage, sound bridges and protected catchments. Publish the maintenance schedule before the next failure.</p><a href="#water">Resilience that lasts <span aria-hidden="true">↗</span></a></article><article><span>02 / THE DRIER SOUTH</span><h3>Make each drop<br/>go further.</h3><p>Repair leaks, assess reuse and prepare fair drought rules. Test any new supply against its full cost.</p><a href="#water">A dependable water plan <span aria-hidden="true">↗</span></a></article><article><span>03 / ALTO &amp; OULUKSEE</span><h3>Join the skills<br/>to the opportunity.</h3><p>Connect the regional capital, the port and local industry to training, homes and usable transport.</p><a href="#homes">Make room near work <span aria-hidden="true">↗</span></a></article></div></div></div></section>
   <section className="cam-plan cam-width" id="plan"><div className="cam-section-heading"><p className="cam-label">The next chapter of SAVE Cambria</p><h2>Good work.<br/>A place to live.<br/><em>A reason to stay.</em></h2><p>The earlier SAVE program set a direction. In 2068, I will connect it to the Alliance’s housing, equipment investment and training plans, with choices shaped by Cambria’s coast, industry and mountain communities.</p></div><nav className="cam-plan-nav" aria-label="Cambria priorities">{priorities.map(p=><a href={`#${p.id}`} key={p.id}>{p.label}<span aria-hidden="true">↓</span></a>)}</nav>{priorities.map(p=><article className="cam-policy" id={p.id} key={p.id}><div><p className="cam-label">{p.label}</p><h3>{p.title}</h3><p>{p.intro}</p></div><div className="cam-details">{p.details.map(([title,body])=><details key={title}><summary>{title}<span aria-hidden="true">+</span></summary><p>{body}</p></details>)}</div></article>)}</section>
   <section className="cam-account" id="accountable"><div className="cam-width"><p className="cam-label">My commitment to you</p><h2>You deserve an MP<br/><em>you can reach.</em></h2><div className="cam-account-grid"><article><h3>Show up.</h3><p>I will publish a regular rotation of constituency meetings in Alto, coastal towns and mountain communities, with telephone appointments for people who cannot travel.</p></article><article><h3>Show the useful results.</h3><p>Every quarter, I will report the decisions still needed, the delays and the agency responsible. Course completion, routes kept open, appointment access and homes completed matter more than announcements.</p></article><article><h3>Respect your money.</h3><p>Projects need an independent case, open contracts and funded upkeep. School and care plans need recurring funding and staff. I will defend property rights, a fair appeal and the same scrutiny for my own side.</p></article></div></div></section>
   <section className="cam-review-alliance cam-width" aria-labelledby="cam-national-title"><div><p className="cam-label">Cambria’s case at the national table</p><h2 id="cam-national-title">Local purpose.<br/><em>Shared strength.</em></h2></div><div><p>The Alliance brings a national housing plan, investment rules and public-service standards. My job is to make them work together here: for the home near the workshop, the road to the harbor and the classroom that leads to a trade.</p><nav aria-label="National commitments behind the Cambria plan"><Link href="/platform/housing/">Homes, tenancies &amp; ownership <span aria-hidden="true">↗</span></Link><Link href="/platform/economy/">Enterprise &amp; investment <span aria-hidden="true">↗</span></Link><Link href="/platform/infrastructure/">Connections with delivery dates <span aria-hidden="true">↗</span></Link><Link href="/platform/education/">Education &amp; practical skills <span aria-hidden="true">↗</span></Link></nav></div></section>
   <section className="cam-invite cam-width"><p className="cam-label">Let’s talk about the place we call home</p><h2>Bring the question<br/><em>you want answered.</em></h2><p>About your harbor. Your journey to work. The business you want to start. A useful campaign starts with the things that matter in everyday life.</p><div><Link className="cam-button" href="/events/#next-generation-economy">Meet Pepe in Cambria <span aria-hidden="true">↗</span></Link><Link className="cam-text-link" href="/platform/mission-statement/">What the Alliance believes <span aria-hidden="true">↗</span></Link></div><CandidateActions name="Pepe Marti Rutte" region="Cambria" commitments={['Connect Ouluksee’s working coast to cold storage, fair access and local opportunity.', 'Back paid technical training, equipment investment and competitive supplier contracts.', 'Build homes near work with secure tenancies and limited ownership help for new supply.', 'Maintain mountain connections and tailor water plans to the wetter north and drier south.', 'Report useful results, recurring service funding and the full cost of major projects.']}/></section>
  </main><PlatformFooter />
 </div>;
}
