import Link from "next/link";

const priorities = [
  { id: "industry", label: "Industry & investment", title: "Make more of what the world needs.", text: "Chasmia has the resources, factories and engineering culture to compete at the highest level. The next step is to turn more local inputs into high value products here at home.", details: [
    ["A Chasberg advanced industry compact", "Bring manufacturers, training providers and infrastructure agencies around one published investment plan for green technology, aviation components and advanced industrial systems. Public support should be competitive, time limited and tied to private investment, skilled jobs and independently reported results."],
    ["Turn resources into finished products", "Use open bidding for shared testing, processing and industrial facilities where a clear business case shows that smaller firms cannot provide them alone. Connect Chasmian producers to the Alliance’s immediate expensing proposal for qualifying machinery, software and clean equipment."],
    ["Keep the fundamentals competitive", "Protect Chasmia’s reputation for fiscal prudence and a predictable tax burden. Publish energy, freight, permitting and workforce constraints for major industrial zones, with a responsible agency and delivery date for every agreed improvement."]
  ]},
  { id: "skills", label: "Skills, research & AI", title: "Give talent a reason to come, and a reason to stay.", text: "Lisieux is already a center for universities, laboratories and computing. That success should open doors for young Chasmians and bring skilled people back to the region.", details: [
    ["Link research to Chasmian firms", "Create open partnerships between Lisieux institutions and employers working in AI, industrial computing, energy and advanced materials. Any public research agreement should publish its purpose, intellectual property terms and the additional investment it brings into Chasmia."],
    ["Build routes into skilled work", "Expand employer designed technical programs in manufacturing, shipbuilding, agriculture and computing. Share apprenticeship administration so smaller firms can participate. Under the Alliance program, eligible people under 25 will receive a suitable work, training or apprenticeship offer within 90 days after four months outside employment or education."],
    ["Welcome Chasmians home", "Publish hard to fill occupations and connect returning residents to employers, housing information and recognition of qualifications. Recruitment incentives should be focused on genuine shortages and reviewed against retention after two years."]
  ]},
  { id: "maritime", label: "Shipbuilding & connections", title: "From Littlewoods to the world.", text: "Littlewoods can anchor a maritime economy that supports design, fabrication, repair and exports across Chasmia, not just activity at the water’s edge.", details: [
    ["A serious shipbuilding pipeline", "Give firms a transparent view of expected public vessel procurement and maintenance needs without promising work before competition. Break suitable contracts into packages that allow specialist Chasmian suppliers to bid, while keeping safety, cost and delivery standards firm."],
    ["Fix the freight links behind the port", "Publish a condition and capacity review of the road, rail and utility links serving Littlewoods and Chasberg. Prioritize maintenance and bottlenecks that hold back several employers, then show capital costs and future upkeep before construction begins."],
    ["Help smaller exporters reach market", "Bring certification, customs and trade finance advice into one regional service connected to the Alliance’s proposed single customs window. Publish fees and processing times so a growing manufacturer can plan an export order with confidence."]
  ]},
  { id: "interior", label: "Interior & communities", title: "Growth that reaches beyond the big hubs.", text: "The interior’s farms and post-industrial communities should share in Chasmia’s renewal. Distance must not decide whether a family can reach work, care or a dependable connection.", details: [
    ["Productive farms, resilient land", "Support practical adoption of precision irrigation, soil monitoring and modern farm equipment where it improves output or water use. Stewardship payments should buy measurable environmental gains without pushing productive family farms off the land."],
    ["Services people can reach", "Coordinate transport around work, college and healthcare appointments, with assisted booking for residents who cannot rely on an app. Work with health providers to identify specialist services that can be delivered through scheduled regional clinics rather than repeated long journeys."],
    ["Measure who benefits from growth", "Report employment, earnings, business formation and infrastructure delivery by community, not only as a regional average. Use those results to target genuine access barriers while keeping grants competitive and subject to the same fiscal rules as the national program."]
  ]},
];

export default function ChasmiaCampaign() {
  return <div className="amb68-root cha68-root">
    <a className="campaign-skip" href="#chasmia-main">Skip to content</a>
    <header className="amb68-header"><Link className="amb68-brand" href="/chasmia/" aria-label="Patrick for Chasmia home"><img src="/images/mr-logo.png" alt="Moderate Reform" width="68" height="42"/><span>PATRICK<br/><small>CHASMIA 2068</small></span></Link><nav aria-label="Chasmia campaign"><a href="#plan">Our plan</a><a href="#choice">The choice</a><a href="#about">Meet Patrick</a><Link href="/">The Alliance <span aria-hidden="true">↗</span></Link></nav></header>
    <main id="chasmia-main">
      <section className="amb68-hero"><div className="amb68-hero-copy"><p className="campaign-label">Moderate Reform · Chasmia · 2068</p><h1>Build the<br/><em>next</em><br/>Chasmia.</h1><p>Patrick Cutter for Chasmia.<br/>Skilled work. Strong industry. Progress that reaches every community.</p><a className="campaign-text-link" href="#plan">See Patrick’s plan <span aria-hidden="true">↓</span></a></div><figure><img src="/images/patrick-campaign-1.png" alt="Patrick Cutter" fetchPriority="high"/><figcaption>PATRICK CUTTER / MODERATE REFORM</figcaption></figure></section>

      <section className="amb68-opening campaign-width"><p className="campaign-label">Chasmia’s next chapter</p><div><h2>We made the transition.<br/><em>Now make it count.</em></h2><div className="amb68-prose"><p>Chasmia once depended too heavily on mining, oil and primary exports. That brought jobs, but it also left communities exposed to every downturn. Young people left, interior towns aged and too much potential went elsewhere.</p><p>The AI and resource boom of the late 2020s and 2030s helped Chasmia change course. Lisieux grew into a research and technology center. Chasberg built a reputation for advanced manufacturing. Littlewoods became a serious shipbuilding hub. Lower costs and sound public finances attracted new firms and workers.</p><p>The job in 2068 is to turn that rebirth into lasting opportunity: more value added here, more routes into skilled work and growth that reaches the interior.</p></div></div></section>

      <section className="amb68-land"><figure><img src="/images/events/chasmia-industry.jpg" alt="Modern industrial work in Chasmia" loading="lazy"/></figure><div><p className="campaign-label">An economy transformed</p><h2>Resources.<br/>Research.<br/><em>Real production.</em></h2><p>Chasmia does not have to choose between its industrial inheritance and a modern economy. Advanced manufacturing, AI, shipbuilding, energy and productive agriculture can reinforce one another when skills and infrastructure keep pace.</p><a className="campaign-text-link" href="#industry">Build the industrial future <span aria-hidden="true">↓</span></a></div></section>

      <section className="amb68-plan campaign-width" id="plan"><div className="amb68-plan-heading"><p className="campaign-label">The Chasmia plan / 2068 to 2072</p><h2>Four engines.<br/><em>One region moving forward.</em></h2><p>These local commitments connect Chasmia’s strengths to the Alliance program. Open each item for the practical steps, safeguards and measures Patrick will take to Parliament.</p></div><nav className="amb68-plan-index" aria-label="Policy topics">{priorities.map(p=><a key={p.id} href={`#${p.id}`}>{p.label}<span aria-hidden="true">↓</span></a>)}</nav>{priorities.map((p,i)=><article className="amb68-policy" id={p.id} key={p.id}><div className="amb68-policy-intro"><p className="campaign-label">0{i+1} / {p.label}</p><h3>{p.title}</h3><p>{p.text}</p></div><div className="belief-accordions">{p.details.map(([heading,body])=><details key={heading}><summary>{heading}<span aria-hidden="true">+</span></summary><p>{body}</p></details>)}</div></article>)}</section>

      <section className="cha68-choice" id="choice"><div className="campaign-width"><p className="campaign-label">The choice in 2068</p><div className="cha68-choice-grid"><div><h2>Forward with a plan.<br/><em>Not backward with a grievance.</em></h2><p>Harry Balls asks Chasmia to return to the politics of permanent anger. Patrick Cutter offers a practical program for investment, skills and accountable delivery.</p></div><div className="cha68-compare"><article><span>HARRY BALLS</span><h3>Old arguments.</h3><p>A campaign built around who to blame, without a credible route from protest to better jobs, stronger services or new investment.</p></article><article><span>PATRICK CUTTER</span><h3>The next chapter.</h3><p>Build on Chasmia’s economic rebirth, keep public finances sound and publish the results community by community.</p></article></div></div></div></section>

      <section className="amb68-pledge"><div className="campaign-width"><p className="campaign-label">Patrick’s standard for delivery</p><h2>Promises you can track.<br/><em>Decisions you can test.</em></h2><div className="amb68-three"><article><h3>Publish the baseline.</h3><p>Start with the condition of Chasmia’s infrastructure, workforce and industrial capacity, so progress is measured against facts rather than slogans.</p></article><article><h3>Name who is responsible.</h3><p>Every regional agreement should show its lead agency, funding source, milestones and maintenance costs before work begins.</p></article><article><h3>Report every quarter.</h3><p>Show what has moved, what has not and why. Break results down by community so growth in one city does not hide stagnation elsewhere.</p></article></div></div></section>

      <section className="amb68-about campaign-width" id="about"><figure><img src="/images/patrick-campaign-2.png" alt="Patrick Cutter" loading="lazy"/></figure><div><p className="campaign-label">Meet Patrick</p><h2>Experience to govern.<br/><em>Discipline to deliver.</em></h2><p>Patrick Cutter has represented Chasmia in Parliament since 2058. He has served as Prime Minister and later as Deputy Prime Minister, experience that taught him both the reach of national government and the importance of clear local accountability.</p><p>His politics are rooted in an uncomplicated test: does government help people build safer, more prosperous lives? For Chasmia, that means dependable roads and services, modern agriculture, skilled industrial work and investment that can survive beyond the next cycle.</p><p>Patrick stands for Moderate Reform within the Liberal-Conservative Alliance. In 2068, he is asking Chasmia for a mandate to consolidate the region’s economic rebirth and make its benefits visible in every community.</p><Link className="campaign-text-link" href="/team/#patrick">Meet the Alliance team <span aria-hidden="true">↗</span></Link></div></section>

      <section className="amb68-alliance campaign-width"><p className="campaign-label">A Chasmian plan. A national partnership.</p><div><h2>Industry with ambition.<br/><em>Government with discipline.</em></h2><p>Patrick’s program connects Chasmia’s industrial strengths to the Alliance commitments on investment, skills, infrastructure and sound public finances. The goal is straightforward: give people and firms the confidence to build here.</p><a className="campaign-text-link" href="/manifesto/caprica-freedom-to-build-2068.pdf" target="_blank" rel="noreferrer">Read the 2068 manifesto · PDF <span aria-hidden="true">↗</span></a></div></section>

      <section className="amb68-action" id="take-part"><div className="campaign-width"><p className="campaign-label">Join the conversation</p><h2>Chasmia’s next chapter<br/><em>needs your voice.</em></h2><div className="amb68-action-grid"><div><h3>Come with a question.</h3><p>Meet Patrick and local employers at the Industry, Skills and Chasmia’s Future town hall in Littlewoods.</p><Link className="campaign-text-link" href="/events/#chasmia-future">See the Chasmia event <span aria-hidden="true">↗</span></Link></div><div><h3>Read the detail.</h3><p>Explore the local commitments and the national program behind them, then share the proposal that matters most to your community.</p><a className="campaign-text-link" href="#plan">Explore the Chasmia plan <span aria-hidden="true">↑</span></a><Link className="campaign-text-link" href="/events/#register">Event participation details <span aria-hidden="true">↗</span></Link></div></div></div></section>
    </main>
    <footer className="amb68-footer campaign-width"><Link className="amb68-brand" href="/chasmia/"><img src="/images/mr-logo.png" alt="Moderate Reform" width="68" height="42"/><span>PATRICK<br/><small>FOR CHASMIA</small></span></Link><p>Moderate Reform · Liberal-Conservative Alliance<br/>Chasmia campaign, 2068</p><Link className="campaign-text-link" href="/">The national campaign <span aria-hidden="true">↗</span></Link></footer>
  </div>;
}
