export const priorities = [
  {slug:'economy',image:'/images/economy.jpg',kicker:'WORK, TAX AND ENTERPRISE',title:'More room to get ahead',headline:'Let effort pay again.',short:'Lower the tax on work, back small business and put competition before political control.',detail:'Raise the tax-free threshold, simplify business taxes and introduce a one-in, two-out rule for costly new regulation. Independent regulators, not ministers, will protect fair prices and open markets.',commitments:['Raise the personal tax-free threshold and index it to wages','Create one simple quarterly return for small firms and sole traders','Require every new regulation to publish its cost to households and business','Open government purchasing to young firms and regional suppliers','Protect independent competition enforcement in concentrated markets']},
  {slug:'security',image:'/images/security.jpg',kicker:'JUSTICE, POLICING AND DEFENSE',title:'Safe streets, secure nation',headline:'Order without overreach.',short:'Visible policing at home and dependable allies across the Columbian community.',detail:'Put more officers where people see them, target organized crime and cyber threats, and give courts the capacity to move cases quickly. Abroad, we will remain a reliable Columbian ally and invest in modern defense.',commitments:['Put neighborhood teams on visible, multi-year staffing plans','Create specialist national units for organized crime, fraud and cyber threats','Fund additional court capacity and digital case management','Guarantee independent review of emergency and surveillance powers','Publish a ten-year defense capability and procurement plan']},
  {slug:'build',image:'/images/build.jpg',kicker:'HOUSING, TRANSPORT AND WATER',title:'Build what we need',headline:'From delay to delivery.',short:'Faster homes, better transport and reliable energy, without years lost to paperwork.',detail:'Create a single approvals pathway for nationally significant projects, unlock housing near transport, and invite competitive investment into rail, ports, water and clean firm power.',commitments:['Set binding decision deadlines for major planning applications','Allow more homes around rapid transit and established town centers','Create regional infrastructure agreements with transparent milestones','Use competitive delivery contracts for rail, ports and water renewal','Publish a national pipeline so builders can invest in people and equipment']},
  {slug:'services',image:'/images/services.jpg',kicker:'HEALTH, EDUCATION AND SKILLS',title:'Services that deliver',headline:'A guarantee of outcomes.',short:'Judge public services by the result for you, not the size of the department.',detail:'Guarantee timely primary care, publish school and hospital outcomes, expand technical pathways and let public, community and independent providers compete to deliver quality care.',commitments:['Introduce a primary-care access guarantee with regional reporting','Publish comparable waiting-time and treatment-outcome dashboards','Protect core literacy and numeracy time in every primary school','Build employer-designed technical academies in all major regions','Fund services around the citizen, whether delivery is public or independent']},
  {slug:'energy',image:'/images/energy.jpg',kicker:'ENERGY AND THE ENVIRONMENT',title:'Clean, firm, affordable power',headline:'Abundance is climate policy.',short:'Build a resilient electricity system that cuts emissions without rationing growth.',detail:'Replace stop-start intervention with a technology-neutral clean power market. Speed up grids, storage and generation while protecting landscapes through clear national standards.',commitments:['Create a single national connection process for new generation','Run long-term auctions for clean, firm capacity and storage','Modernize the grid before congestion becomes a growth tax','Price pollution consistently and return proceeds through lower taxes','Pay host communities a share of major energy-project revenues']},
  {slug:'regions',image:'/images/farm.jpg',kicker:'FARMS, ISLANDS AND REGIONS',title:'Power closer to home',headline:'One country, many strengths.',short:'Give regions the tools and revenue to shape their own growth.',detail:'Move practical decisions closer to communities, secure clean rural water and connect producers, islands and smaller cities to national and Columbian markets.',commitments:['Give regions multi-year transport and skills budgets','Create a clean-water renewal fund with public quality reporting','Upgrade farm-to-port freight corridors and cold-chain capacity','Give Myrati greater authority over tourism and local transport','Share royalties from nationally significant projects with host regions']},
  {slug:'government',image:'/images/digital.jpg',kicker:'DEMOCRACY AND GOVERNMENT',title:'A state worthy of trust',headline:'Open by default.',short:'Protect constitutional government and make the public sector radically easier to see and use.',detail:'Rights, checks and honest administration are not obstacles to action. They are how lasting reform earns consent. LCA will pair a capable state with real limits on political power.',commitments:['Publish contracts, performance data and ministerial meetings by default','Create one secure digital front door for national services','Require sunset votes for emergency powers','Strengthen independent fiscal and electoral institutions','Give citizens a right to a timely decision from public agencies']},
  {slug:'world',image:'/images/port.jpg',kicker:'TRADE AND COLUMBIA',title:'Confident in the world',headline:'Open, allied, prepared.',short:'Use Caprica’s commercial strength and Columbian ties to keep the country secure and prosperous.',detail:'Caprica should be a dependable Columbian ally, a champion of open trade and a practical partner across the Aortic Sea. Economic security and national security will be planned together.',commitments:['Deepen the Columbian single market in services and digital trade','Create secure supply agreements for medicines, energy and critical technology','Expand port capacity and trusted-trader lanes','Coordinate cyber defense with Columbian partners','Tie development partnerships to transparent, measurable outcomes']}
];

type Candidate = {slug:string;name:string;first:string;region:string;seat:string;image:string;quote:string;bio:string;focus:string[];campaignSite?:string;campaignLabel?:string};

export const candidates: Candidate[] = [
  {slug:'alan',name:'Alan Bluespan III',first:'Alan',region:'VICE PRESIDENT',seat:'National ticket',image:'/images/alan.png',quote:'“The citizen, not the system, should be the protagonist.”',bio:'An economist, entrepreneur and reformer from Chasmia, Alan enters 2064 with a record of opening utilities to competition, strengthening the national credit rating and defending constitutional order through the courts. His next program joins disciplined public finances with new housing, modern transport and energy investment, while setting consistent national standards for accountable policing.',focus:['Constitutional government','Competition and sound finances','Housing and infrastructure']},
  {slug:'alistair',name:'Alistair Foulke-McKeon',first:'Alistair',region:'AMBROSIA',seat:'Candidate for MP',image:'/images/alistair.png',quote:'“Recovery was the beginning. Now Ambrosia must grow.”',bio:'Alistair is standing on four years of work to renew water systems, strengthen agriculture and rebuild the infrastructure rural communities depend on. His next plan takes Ambrosia from recovery to growth, opening new export markets, supporting local food processing, extending dependable rural broadband and protecting Mount Ambrosia as both a natural inheritance and a source of sustainable opportunity.',focus:['Farm exports and local processing','Clean water and rural broadband','Mount Ambrosia conservation'],campaignSite:'/ambrosia',campaignLabel:'Visit Alistair’s Ambrosia campaign'},
  {slug:'patrick',name:'Patrick Cutter',first:'Patrick',region:'CHASMIA',seat:'Candidate for MP',image:'/images/patrick.png',quote:'“We cannot, and we will not, go back.”',bio:'Chasmia’s MP since 2058, Patrick previously served as Prime Minister and later Deputy Prime Minister. His regional plan starts with dependable roads and infrastructure, then builds on Chasmia’s agricultural strength through smart irrigation and modern farm technology. He is also campaigning for specialist healthcare closer to home, stronger mountain tourism and skilled jobs from wind and hydroelectric power.',focus:['Roads and rural infrastructure','High-tech agriculture','Healthcare and clean energy'],campaignSite:'https://manualalan.github.io/patrick-cutter-2064/',campaignLabel:'Visit Patrick’s Chasmia campaign'},
  {slug:'stoner',name:'JB Stoner',first:'JB',region:'MYRATI',seat:'Candidate for MP',image:'/images/stoner.png',quote:'“We export Myratian goods, and import opportunities.”',bio:'JB offers steady leadership after years in which Myrati chose recovery over political violence. Through the Prosper Myrati program, he is working to turn Port Aaron into a commercial gateway with deep-water berths, shipbuilding and repair, better road and rail links, an expanded airport and Free Trade Port status. His plan also supports students who study on the mainland and bring their skills home.',focus:['Port Aaron and free trade','Airport, road and rail links','Peace, education and opportunity'],campaignSite:'https://manualalan.github.io/JB-Stoner-2064/',campaignLabel:'Visit JB’s Myrati campaign'},
  {slug:'tony',name:'Tony Blair',first:'Tony',region:'OPLANA',seat:'Candidate for MP',image:'/images/tony-blair.png',quote:'“A safer, freer Oplana, easier to build in, better to live in.”',bio:'Tony is standing for practical optimism in Oplana, firm action against gangs alongside a credible route out of addiction and violence. His plan combines visible neighborhood patrols and accountable safety audits with a new recovery hub, homes on derelict land, safer rentals and a Market Mile reset that cuts permit costs for local traders. Every school leaver should reach a job, apprenticeship or training place within six months.',focus:['Safe streets and recovery','Homes on derelict land','Local business and apprenticeships'],campaignSite:'https://manualalan.github.io/tony-blair-oplana/',campaignLabel:'Visit Tony’s Oplana campaign'},
  {slug:'libero',name:'Roberto Libero',first:'Roberto',region:'RENO',seat:'Candidate for MP',image:'/images/libero.jpg',quote:'“Keep Reno moving, keep it safe, and keep opportunity within reach.”',bio:'Roberto champions the entrepreneurs, commuters and families who make Reno one of Caprica’s most dynamic communities. He is focused on safer neighborhoods, better links to Montiablo and more housing choices close to jobs, schools and everyday services.',focus:['Faster commutes','Safer neighborhoods','Housing choice']},
  {slug:'ronan',name:'Ronan Hayward',first:'Ronan',region:'MONTIABLO',seat:'Candidate for MP',image:'/images/ronan.png',quote:'“This city does not need a spectator.”',bio:'An experienced reformer and former Mayor-Governor, Ronan is campaigning to make the capital work as one connected region. He backs a single CATA network and fare across bus, tram, metro, ferry and regional rail, firm public oversight of the New Homerville energy project, and a one-stop launch lane for small firms and cultural venues. Public delivery dashboards would show residents exactly what government has promised and completed.',focus:['One network, one fare','Affordable power with oversight','Open government and enterprise'],campaignSite:'https://manualalan.github.io/ronan-hayward-montiablo/',campaignLabel:'Visit Ronan’s Montiablo campaign'},
  {slug:'pepe',name:'Pepe Marti Rutte',first:'Pepe',region:'CAMBRIA',seat:'Candidate for MP',image:'/images/pepe.png',quote:'“Cambria should be a place where a good idea can become a good living.”',bio:'Pepe is standing for a more enterprising, connected and affordable Cambria. His campaign is focused on opening doors for young workers and local firms, expanding practical training, and making it easier to build homes near jobs and transport. He wants national government to give Cambrian communities the tools to grow on their own strengths.',focus:['Skills for young workers','Backing local enterprise','Homes near transport'],campaignSite:'https://manualalan.github.io/pepe-marti-cambria/',campaignLabel:'Visit Pepe’s Cambria campaign'},
  {slug:'pagi',name:'Rupert Pagi Shaw',first:'Rupert',region:'KALAHOOSKA',seat:'Candidate for MP',image:'/images/pagi-2064.png',quote:'“Kalahooska deserves a strong voice in the room where national decisions are made.”',bio:'Rupert is campaigning to connect Kalahooska’s communities to opportunity without losing the character that makes the region distinct. His priorities are dependable transport, resilient local services and a practical settlement that gives regional leaders more authority over the decisions closest to home.',focus:['Regional transport','Resilient local services','Decisions closer to home'],campaignSite:'https://manualalan.github.io/rupert-pagi-kalahooska/',campaignLabel:'Visit Rupert’s Kalahooska campaign'},
  {slug:'mathieu',name:'Mathieu Jeon',first:'Mathieu',region:'PLEUCADEUC',seat:'Candidate for MP',image:'/images/mathieu.jpg',quote:'“Staying home should never mean standing still.”',bio:'Born and raised in Pleucadeuc, Mathieu sees representation as a service and wants his generation to build ambitious lives without leaving its roots behind. His central commitment is a full high-speed upgrade for the Valcartier, Fiévreau and Syon corridor, coordinated with local rail and buses. The investment would support Caprican apprenticeships, housing near stations and a strong voice for Pleucadeuc’s Gallic-speaking communities.',focus:['Southern high-speed rail','Local connections and housing','Gallic life and opportunity'],campaignSite:'https://manualalan.github.io/mathieu-jeon-pleucadeuc/',campaignLabel:'Visit Mathieu’s Pleucadeuc campaign'}
];

export const events=[
  {slug:'caprica-we-can-build',day:'28',month:'AUG',time:'18:30',type:'ALLIANCE FORUM',title:'The Caprica We Can Build',place:'City Hall · Montiablo',description:'What should a better Caprica feel like in everyday life? Bring your questions about homes, work and the responsibilities of government.',image:'/images/events/montiablo-hall.jpg',imagePosition:'center 52%'},
  {slug:'ambrosia-roundtable',day:'04',month:'SEP',time:'10:00',type:'REGIONAL VISIT',title:'Ambrosia Farm & Water Roundtable',place:'Meridian Cooperative · Ambrosia',description:'A conversation with the people who work the land. Talk about reliable water, getting produce to market and making a living in rural Caprica.',image:'/images/events/ambrosia-fields.jpg',imagePosition:'center 48%'},
  {slug:'chasmia-future',day:'12',month:'SEP',time:'19:00',type:'TOWN HALL',title:'Industry, Skills and Chasmia’s Future',place:'Littlewoods Exchange · Chasmia',description:'Meet Patrick Cutter to talk about learning a trade, running a workshop and keeping skilled work in Chasmia. Apprentices and employers welcome.',image:'/images/events/chasmia-industry.jpg',imagePosition:'center 42%'},
  {slug:'open-seas-open-markets',day:'20',month:'SEP',time:'17:30',type:'PORT FORUM',title:'Open Seas, Open Markets',place:'Port Aaron Maritime Terminal · Myrati',description:'Come down to Port Aaron to discuss the work behind an island economy: building ships, moving goods and keeping our connections to the world secure.',image:'/images/events/myrati-port.jpg',imagePosition:'center 48%'},
  {slug:'safe-streets-second-chances',day:'27',month:'SEP',time:'18:00',type:'COMMUNITY WALK',title:'Safe Streets, Second Chances',place:'Market Mile · Oplana',description:'Walk Market Mile with residents and local traders, then join a conversation about safer streets, recovery and a neighbourhood people want to spend time in.',image:'/images/events/oplana-market.jpg',imagePosition:'center 46%'},
  {slug:'southern-line',day:'03',month:'OCT',time:'18:45',type:'TRANSPORT ASSEMBLY',title:'The Southern Line',place:'Valcartier Central · Pleucadeuc',description:'Ask Mathieu Jeon what faster rail would mean for your commute and your town. A conversation about the southern line, its stations and the homes around them.',image:'/images/events/pleucadeuc-station.jpg',imagePosition:'center 52%'},
  {slug:'homes-within-reach',day:'10',month:'OCT',time:'18:30',type:'BUILDING FORUM',title:'Homes Within Reach',place:'Riverside Works · Reno',description:'Finding a home should not mean leaving your life behind. Talk with renters, builders and neighbours about making more room in Reno.',image:'/images/events/reno-waterfront.jpg',imagePosition:'center 52%'},
  {slug:'next-generation-economy',day:'17',month:'OCT',time:'17:00',type:'CAMPUS FORUM',title:'The Next Good Idea',place:'Cambria Technical University · Cambria',description:'Meet Pepe Marti Rutte and local founders to talk about getting started, finding work and turning something you care about into something you can build.',image:'/images/events/cambria-campus.jpg',imagePosition:'center 50%'}
];
