export const priorities = [
  {slug:'economy',image:'/images/economy.jpg',kicker:'WORK, TAX AND ENTERPRISE',title:'More room to get ahead',headline:'Let effort pay again.',short:'Lower the tax on work, back small business and put competition before political control.',detail:'Raise the tax-free threshold, simplify business taxes and introduce a one-in, two-out rule for costly new regulation. Independent regulators, not ministers, will protect fair prices and open markets.',commitments:['Raise the personal tax-free threshold and index it to wages','Create one simple quarterly return for small firms and sole traders','Require every new regulation to publish its cost to households and business','Open government purchasing to young firms and regional suppliers','Protect independent competition enforcement in concentrated markets']},
  {slug:'security',image:'/images/security.jpg',kicker:'JUSTICE, POLICING AND DEFENSE',title:'Safe streets, secure nation',headline:'Order without overreach.',short:'Visible policing at home and dependable allies across the Columbian community.',detail:'Put more officers where people see them, target organized crime and cyber threats, and give courts the capacity to move cases quickly. Abroad, we will remain a reliable Columbian ally and invest in modern defense.',commitments:['Put neighborhood teams on visible, multi-year staffing plans','Create specialist national units for organized crime, fraud and cyber threats','Fund additional court capacity and digital case management','Guarantee independent review of emergency and surveillance powers','Publish a ten-year defense capability and procurement plan']},
  {slug:'build',image:'/images/build.jpg',kicker:'HOUSING, TRANSPORT AND WATER',title:'Build what we need',headline:'From delay to delivery.',short:'Faster homes, better transport and reliable energy, without years lost to paperwork.',detail:'Create a single approvals pathway for nationally significant projects, unlock housing near transport, and invite competitive investment into rail, ports, water and clean firm power.',commitments:['Set binding decision deadlines for major planning applications','Allow more homes around rapid transit and established town centers','Create regional infrastructure agreements with transparent milestones','Use competitive delivery contracts for rail, ports and water renewal','Publish a national pipeline so builders can invest in people and equipment']},
  {slug:'services',image:'/images/services.jpg',kicker:'HEALTH, EDUCATION AND SKILLS',title:'Services that deliver',headline:'A guarantee of outcomes.',short:'Judge public services by the result for you, not the size of the department.',detail:'Guarantee timely primary care, publish school and hospital outcomes, expand technical pathways and let public, community and independent providers compete to deliver quality care.',commitments:['Introduce a primary-care access guarantee with regional reporting','Publish comparable waiting-time and treatment-outcome dashboards','Protect core literacy and numeracy time in every primary school','Build employer-designed technical academies in all major regions','Fund services around the citizen, whether delivery is public or independent']},
  {slug:'energy',image:'/images/energy.jpg',kicker:'ENERGY AND THE ENVIRONMENT',title:'Clean, firm, affordable power',headline:'Abundance is climate policy.',short:'Build a resilient electricity system that cuts emissions without rationing growth.',detail:'Replace stop-start intervention with a technology-neutral clean power market. Speed up grids, storage and generation while protecting landscapes through clear national standards.',commitments:['Create a single national connection process for new generation','Run long-term auctions for clean, firm capacity and storage','Modernize the grid before congestion becomes a growth tax','Price pollution consistently and return proceeds through lower taxes','Pay host communities a share of major energy-project revenues']},
  {slug:'regions',image:'/images/farm.jpg',kicker:'FARMS, ISLANDS AND REGIONS',title:'Power closer to home',headline:'One country, many strengths.',short:'Give regions the tools and revenue to shape their own growth.',detail:'Move practical decisions closer to communities, secure clean rural water and connect producers, islands and smaller cities to national and Columbian markets.',commitments:['Give regions multi-year transport and skills budgets','Create a clean-water renewal fund with public quality reporting','Upgrade farm-to-port freight corridors and cold-chain capacity','Give Myrati greater authority over tourism and local transport','Share royalties from nationally significant projects with host regions']},
  {slug:'government',image:'/images/digital.jpg',kicker:'DEMOCRACY AND GOVERNMENT',title:'A state worthy of trust',headline:'Open by default.',short:'Protect constitutional government and make the public sector radically easier to see and use.',detail:'Rights, checks and honest administration are not obstacles to action. They are how lasting reform earns consent. LCA will pair a capable state with real limits on political power.',commitments:['Publish contracts, performance data and ministerial meetings by default','Create one secure digital front door for national services','Require sunset votes for emergency powers','Strengthen independent fiscal and electoral institutions','Give citizens a right to a timely decision from public agencies']},
  {slug:'world',image:'/images/port.jpg',kicker:'TRADE AND COLUMBIA',title:'Confident in the world',headline:'Open, allied, prepared.',short:'Use Caprica’s commercial strength and Columbian ties to keep the country secure and prosperous.',detail:'Caprica should be a dependable Columbian ally, a champion of open trade and a practical partner across the Aortic Sea. Economic security and national security will be planned together.',commitments:['Deepen the Columbian single market in services and digital trade','Create secure supply agreements for medicines, energy and critical technology','Expand port capacity and trusted-trader lanes','Coordinate cyber defense with Columbian partners','Tie development partnerships to transparent, measurable outcomes']}
];

type Candidate = {slug:string;name:string;first:string;region:string;seat:string;image:string;quote:string;bio:string;focus:string[];campaignSite?:string;campaignLabel?:string};

export const candidates: Candidate[] = [
  {slug:'alistair',name:'Alistair Foulke-McKeon',first:'Alistair',region:'AMBROSIA',seat:'Candidate for MP',image:'/images/alistair.png',quote:'“A future you can build here.”',bio:'Raised on the Foulke family estate in rural Ambrosia and first elected in 2040, Alistair is standing for the People’s Party within the Alliance. His plan starts with clean water and dependable farm-to-market connections, then builds on those foundations: more local food processing, homes with services and training linked to rural employers. He wants investment around Mount Ambrosia to sustain local livelihoods while respecting its land and water.',focus:['Clean water and connected towns','Farm exports and local processing','Homes and rural skills'],campaignSite:'/alistair-foulke-mckeon/',campaignLabel:'Visit Alistair’s Ambrosia campaign'},
  {slug:'david',name:'David Cutter',first:'David',region:'CHASMIA',seat:'Candidate for MP',image:'/images/chasmia/david-cutter-team.jpg',quote:'“We cannot, and we will not, go back.”',bio:'The son of Patrick and Evelyn Cutter and older brother of Erica, David joined the CLA and Moderate Reform while studying at the University of Ambarino. He worked in the engineering industry after graduation and is now a news journalist at the Caprican Herald. He plans to succeed his father when Patrick retires, with a focus on skilled work, investment and opportunities for Chasmia’s next generation.',focus:['Advanced industry and investment','Skills, research and AI','Shipbuilding and connected communities'],campaignSite:'/david-cutter/',campaignLabel:'Visit David’s Chasmia campaign'},
  {slug:'stoner',name:'JB Stoner',first:'JB',region:'MYRATI',seat:'Candidate for MP',image:'/images/stoner.png',quote:'“We export Myratian goods, and import opportunities.”',bio:'JB is campaigning for a confident, outward-looking Myrati where every community has a stake in the island’s future. Through the Prosper Myrati program, he is working to turn Port Aaron into a commercial gateway with deep-water berths, shipbuilding and repair, better road and rail links, an expanded airport and Free Trade Port status. His plan also supports students who study on the mainland and bring their skills home.',focus:['Port Aaron and free trade','Airport, road and rail links','Peace, education and opportunity'],campaignSite:'/jb-stoner/',campaignLabel:'Visit JB’s Myrati campaign'},
  {slug:'tony',name:'Tony Blair',first:'Tony',region:'OPLANA',seat:'Candidate for MP',image:'/images/tony-blair.png',quote:'“Safety and liberty belong together.”',bio:'Tony’s Oplana plan connects safer streets to a neighborhood that can flourish. He backs focused action against gangs, independent oversight of police powers and a recovery hub linking treatment to a route back into work. Homes on derelict land, enforceable rental standards and simpler Market Mile permits would give residents and traders more room to build. His test is practical: safer journeys, doors reopening and lasting routes into skilled work.',focus:['Safe streets and recovery','Homes on derelict land','Local business and apprenticeships'],campaignSite:'/tony-blair/',campaignLabel:'Visit Tony’s Oplana campaign'},
  {slug:'libero',name:'Roberto Libero',first:'Roberto',region:'RENO',seat:'Candidate for MP',image:'/images/libero.jpg',quote:'“A good life. On solid ground.”',bio:'The son of a defense attorney, Roberto became a respected constitutional law professor before entering politics out of concern for parliamentary sovereignty. Conservative in conviction and pragmatic in method, he brings a disciplined focus on accountable government, predictable rules and responsible public spending. His Reno campaign connects those principles to dependable regional transport, thriving local businesses, safe neighborhoods and housing choices through every stage of life.',focus:['Accountable government','One connected region','Quality of life in Reno'],campaignSite:'/roberto-libero/',campaignLabel:'Visit Roberto’s Reno campaign'},
  {slug:'jon',name:'Jon Fraser',first:'Jon',region:'MONTIABLO',seat:'Candidate for MP',image:'/images/jon-fraser.jpg',quote:'“This city does not need a spectator.”',bio:'Montiablo’s Attorney General for eight years, Jon is campaigning to make the capital work as one connected region. He backs a single CATA network and fare across bus, tram, metro, ferry and regional rail, firm public oversight of the New Homerville energy project, and a one-stop launch lane for small firms and cultural venues. Public delivery dashboards would show residents exactly what government has promised and completed.',focus:['One network, one fare','Affordable power with oversight','Open government and enterprise'],campaignSite:'/jon-fraser/',campaignLabel:'Visit Jon’s Montiablo campaign'},
  {slug:'pepe',name:'Pepe Marti Rutte',first:'Pepe',region:'CAMBRIA',seat:'Candidate for MP',image:'/images/pepe.png',quote:'“Cambria should be a place where a good idea can become a good living.”',bio:'Pepe’s Cambria plan is shaped by its working coast, mountain communities and industrial skills. He wants more of the value of Ouluksee’s catch to stay locally, practical training for marine and manufacturing firms, and homes within reach of work. Reliable mountain roads and distinct water plans for the wetter north and drier south connect that economic ambition to everyday life across the region.',focus:['Working coast and skilled industry','Mountain connections and reliable water','Homes near work'],campaignSite:'/pepe-marti-rutte/',campaignLabel:'Visit Pepe’s Cambria campaign'},
  {slug:'pagi',name:'Rupert Pagi Shaw',first:'Rupert',region:'KALAHOOSKA',seat:'Candidate for MP',image:'/images/pagi-2064.png',quote:'“Growth should leave a place stronger than it found it.”',bio:'Rupert links Kalahooska’s forestry economy to a wider case for local opportunity: skilled processing, homes in serviced towns and roads that keep communities connected. He backs sustainable harvesting and restoration alongside a fair opening for smaller suppliers. His regional settlement would put practical decisions closer to home, with the funding, independent audit and public reporting needed to make local authority meaningful.',focus:['Working forests and local enterprise','Homes and resilient connections','Decisions closer to home'],campaignSite:'/rupert-pagi-shaw/',campaignLabel:'Visit Rupert’s Kalahooska campaign'},
  {slug:'mathieu',name:'Mathieu Jeon',first:'Mathieu',region:'PLEUCADEUC',seat:'Candidate for MP',image:'/images/mathieu.jpg',quote:'“Staying home should never mean standing still.”',bio:'Born and raised in Pleucadeuc, Mathieu wants stronger southern connections without losing what makes the region home. He backs a high-speed upgrade for the Valcartier, Fiévreau and Syon corridor in independently costed stages, coordinated with local rail and buses. Homes near stations, Caprican apprenticeships and space for local enterprise would help towns share the benefit, alongside coastal resilience and a strong voice for Gallic life.',focus:['Southern high-speed rail','Local connections and housing','Gallic life and opportunity'],campaignSite:'/mathieu-jeon/',campaignLabel:'Visit Mathieu’s Pleucadeuc campaign'}
];

export const events=[
  {slug:'caprica-we-can-build',day:'28',month:'AUG',time:'18:30',type:'ALLIANCE FORUM',title:'The Caprica We Can Build',place:'City Hall · Montiablo',description:'What should a better Caprica feel like in everyday life? Bring your questions about homes, work and the responsibilities of government.',image:'/images/events/montiablo-hall.jpg',imagePosition:'center 52%'},
  {slug:'ambrosia-roundtable',day:'04',month:'SEP',time:'10:00',type:'REGIONAL VISIT',title:'Ambrosia Farm & Water Roundtable',place:'Meridian Cooperative · Ambrosia',description:'A conversation with the people who work the land. Talk about reliable water, getting produce to market and making a living in rural Caprica.',image:'/images/events/ambrosia-fields.jpg',imagePosition:'center 48%'},
  {slug:'chasmia-future',day:'12',month:'SEP',time:'19:00',type:'TOWN HALL',title:'Industry, Skills and Chasmia’s Future',place:'Littlewoods Exchange · Chasmia',description:'Meet David Cutter to talk about learning a trade, running a workshop and keeping skilled work in Chasmia. Apprentices and employers welcome.',image:'/images/events/chasmia-industry.jpg',imagePosition:'center 42%'},
  {slug:'open-seas-open-markets',day:'20',month:'SEP',time:'17:30',type:'PORT FORUM',title:'Open Seas, Open Markets',place:'Port Aaron Maritime Terminal · Myrati',description:'Come down to Port Aaron to discuss the work behind an island economy: building ships, moving goods and keeping our connections to the world secure.',image:'/images/events/myrati-port.jpg',imagePosition:'center 48%'},
  {slug:'safe-streets-second-chances',day:'27',month:'SEP',time:'18:00',type:'COMMUNITY WALK',title:'Safe Streets, Second Chances',place:'Market Mile · Oplana',description:'Walk Market Mile with residents and local traders, then join a conversation about safer streets, recovery and a neighborhood people want to spend time in.',image:'/images/events/oplana-market.jpg',imagePosition:'center 46%'},
  {slug:'southern-line',day:'03',month:'OCT',time:'18:45',type:'TRANSPORT ASSEMBLY',title:'The Southern Line',place:'Valcartier Central · Pleucadeuc',description:'Ask Mathieu Jeon what faster rail would mean for your commute and your town. A conversation about the southern line, its stations and the homes around them.',image:'/images/events/pleucadeuc-station.jpg',imagePosition:'center 52%'},
  {slug:'homes-within-reach',day:'10',month:'OCT',time:'18:30',type:'BUILDING FORUM',title:'Homes Within Reach',place:'Riverside Works · Reno',description:'Finding a home should not mean leaving your life behind. Talk with renters, builders and neighbors about making more room in Reno.',image:'/images/events/reno-waterfront.jpg',imagePosition:'center 52%'},
  {slug:'next-generation-economy',day:'17',month:'OCT',time:'17:00',type:'CAMPUS FORUM',title:'The Next Good Idea',place:'Cambria Technical University · Cambria',description:'Meet Pepe Marti Rutte and local founders to talk about getting started, finding work and turning something you care about into something you can build.',image:'/images/events/cambria-campus.jpg',imagePosition:'center 50%'}
];
