import type { Metadata } from 'next';
import AllianceCandidateStory, { CandidateStory } from '../components/AllianceCandidateStory';
export const metadata: Metadata = { title:'Tony Blair for Oplana | Alliance 2068', description:'Tony Blair’s 2068 plan for safer streets, second chances, homes and local enterprise in Oplana.' };
const story: CandidateStory = {
 name:'Tony Blair', region:'Oplana', portrait:'/images/tony-blair.png', hero:'/images/events/oplana-market.jpg', heroAlt:'Shops and pedestrians along a lively neighborhood market street', theme:'oplana',
 eyebrow:'Tony Blair for Oplana · Alliance 2068', headline:'Proud streets.', accent:'Fresh chances.', deck:'Safe enough to flourish. Free enough to make your own way.', belief:'“Safety and liberty belong together.”',
 introduction:['I believe the first duty of government is to protect the freedom of ordinary people to live without fear. That means confronting violence and organized crime. It also means using public power with discipline and giving people a credible route out of addiction and offending.','On Market Mile, safety, homes and enterprise meet on the same street. A trader needs customers who feel welcome. A new home needs services that work. Someone rebuilding a life needs a route into paid work. My Oplana plan treats these as parts of the same job.'],
 promise:'I will be firm about harm, honest about what prevents it and impatient with excuses.', eventHref:'/events/#safe-streets-second-chances', eventLabel:'Safe Streets, Second Chances',
 planTitle:'A stronger neighborhood, block by block.',
 planIntro:'Make streets safer, put derelict land to use and give recovery a route into lasting work. These proposals bring Oplana’s everyday needs into the Alliance’s national program, with clear limits on public power and honest funding.',
 commitmentCopy:['I will bring residents, traders and the responsible agencies into the same conversation, then publish what was agreed and what is still unresolved. Safety reports must show follow-up and outcomes, while protecting victims and private casework.','A recovery hub needs clinicians and dependable funding, just as new homes need water and transport. I will seek those agreements before claiming delivery, test results openly and scrutinize the money spent in Oplana’s name.'],
 invitationTitle:'What would help your street thrive?',
 invitationCopy:'Walk Market Mile with residents and traders. Bring the missing crossing, the stalled business idea or the question about recovery that deserves a clear answer.',
 chapters:[
  {label:'Safe streets',title:'A safe walk home should be ordinary.',intro:'A busy, welcoming street starts with confidence that harm will be taken seriously.',points:[['Publish the safety picture','Map repeat violence, theft and dangerous public spaces without identifying victims. Set neighborhood priorities with residents and report response times, case follow-up and outcomes every quarter.'],['Focused policing, clear limits','Put visible teams in the places facing repeat harm, backed by specialist action against gangs and illegal weapons. Preserve independent complaints, body camera rules and judicial oversight of intrusive powers.'],['Fix the places that feel unsafe','Repair failed lighting, unsafe crossings and neglected public spaces through a published street program. Work with Montiablo and Reno on CATA connections after dark, so staff and customers have a dependable way home.']]},
  {label:'Recovery',title:'A second chance must lead somewhere.',intro:'Treatment, recovery and a route back into work should connect, rather than leave people between services.',points:[['Make the Oplana Recovery Hub work','Seek an agreed service plan bringing assessment, treatment, mental health support and employment advice together. Establish clinical leadership, staffing and funding before opening. Publish access times, continuity of care and independent outcome reviews.'],['A firm route out of gangs','Offer intensive mentoring, education and paid training to people who leave organized crime, alongside enforcement for those who continue to harm others. Safeguard victims and staff, and test the program against sustained employment and reduced reoffending.'],['Support families carrying the weight','Give families a named contact and clear referral route, protect children at risk and connect unpaid caregivers to the Alliance’s respite commitment. Respect consent and privacy when agencies share information.']]},
  {label:'Homes',title:'Build where life already happens.',intro:'Derelict land should become homes, streets and opportunity.',points:[['Homes on brownfield land','Identify serviced sites near transport and established shops. Publish ownership, cleanup needs and planning milestones, then invite builders of different sizes to compete.'],['Safer, fairer renting','Enforce basic safety standards, make deposits portable and give tenants and landlords a fast route through disputes. Keep rules clear enough for responsible small landlords to remain.'],['Services before the ribbon cutting','Agree water, school places, crossings and local transport alongside major development, with the funding and delivery sequence visible before construction begins.']]},
  {label:'Local enterprise',title:'Let Market Mile move again.',intro:'A strong neighborhood needs people willing to open the door each morning.',points:[['One route through permits','Give routine business and premises applications a named officer, clear fees and published deadlines. Delays trigger escalation, while safety standards remain firm. Reuse verified information so an applicant does not have to start again at every department.'],['A route into lasting work','Ask local employers and colleges to offer paid placements and apprenticeships tied to recognized skills. Use shared administration so independent traders can take part. Publish completion and progression into sustained work.'],['Bring empty shops back','Use transparent temporary-use licenses for vacant units with clear access, noise and safety conditions. Coordinate deliveries and evening transport with traders and residents, giving a new business a fair chance without shifting unreasonable costs onto neighbors.']]}
 ]
};
export default function TonyBlair(){return <AllianceCandidateStory story={story}/>;}
