import type { Metadata } from 'next';
import AllianceCandidateStory, { CandidateStory } from '../components/AllianceCandidateStory';
export const metadata: Metadata = { title:'Tony Blair for Oplana | Alliance 2068', description:'Tony Blair’s 2068 plan for safer streets, second chances, homes and local enterprise in Oplana.' };
const story: CandidateStory = {
 name:'Tony Blair', region:'Oplana', portrait:'/images/tony-blair.png', hero:'/images/events/oplana-market.jpg', heroAlt:'Shops and pedestrians along a lively neighborhood market street', theme:'oplana',
 eyebrow:'Tony Blair for Oplana · Alliance 2068', headline:'Proud streets.', accent:'Fresh chances.', deck:'Safe enough to flourish. Free enough to make your own way.', belief:'“Safety and liberty belong together.”',
 introduction:['I believe the first duty of government is to protect the freedom of ordinary people to live without fear. That means confronting violence and organized crime. It also means using public power with discipline and treating every person as capable of rebuilding a life.','Oplana is at its best when a busy street feels welcoming, a trader can take a chance and a young person can see a route into work. I am standing to make that everyday confidence possible again.'],
 promise:'I will be firm about harm, honest about what prevents it and impatient with excuses.', eventHref:'/events/#safe-streets-second-chances', eventLabel:'Safe Streets, Second Chances',
 chapters:[
  {label:'Safe streets',title:'Take back every block.',intro:'Visible order is the foundation of an open neighborhood.',points:[['Publish the safety picture','Map repeat violence, theft and dangerous public spaces without identifying victims. Set neighborhood priorities with residents and report response times, case follow up and outcomes every quarter.'],['Focused policing, clear limits','Put visible teams in the places facing repeat harm, backed by specialist action against gangs and illegal weapons. Preserve independent complaints, body camera rules and judicial oversight of intrusive powers.'],['Design out the easy opportunities','Repair failed lighting, unsafe crossings and neglected public spaces through a published street programme. Coordinate transport after dark so staff and customers can get home safely.']]},
  {label:'Recovery',title:'A second chance must lead somewhere.',intro:'Leaving addiction or violence takes courage. Public services should meet it with a credible route forward.',points:[['Open the Oplana Recovery Hub','Bring assessment, treatment, mental health support and employment advice into one accountable service. Publish access times, completion rates and independent outcome reviews.'],['A firm route out of gangs','Offer intensive mentoring, education and paid training to people who leave organized crime, alongside enforcement for those who continue to harm others. Safeguard victims and staff.'],['Support families carrying the weight','Give families a named contact and clear referral route, protect children at risk and connect unpaid caregivers to the Alliance’s respite commitment.']]},
  {label:'Homes',title:'Build where life already happens.',intro:'Derelict land should become homes, streets and opportunity.',points:[['Homes on brownfield land','Identify serviced sites near transport and established shops. Publish ownership, cleanup needs and planning milestones, then invite builders of different sizes to compete.'],['Safer, fairer renting','Enforce basic safety standards, make deposits portable and give tenants and landlords a fast route through disputes. Keep rules clear enough for responsible small landlords to remain.'],['Services before the ribbon cutting','Agree water, school places, crossings and local transport alongside major development, with the funding and delivery sequence visible before construction begins.']]},
  {label:'Local enterprise',title:'Let Market Mile move again.',intro:'A strong neighborhood needs people willing to open the door each morning.',points:[['One route through permits','Give routine business and premises applications a named officer, clear fees and published deadlines. Delays trigger escalation, while safety standards remain firm.'],['A first step into work','Ask local employers and colleges to offer paid placements and apprenticeships tied to recognized skills. Publish progression into sustained work.'],['Bring empty shops back','Use transparent temporary use licenses for vacant units with clear access, noise and safety conditions. Coordinate deliveries and evening transport with traders and residents.']]}
 ]
};
export default function TonyBlair(){return <AllianceCandidateStory story={story}/>;}
