import type { Metadata } from 'next';
import AllianceCandidateStory, { CandidateStory } from '../components/AllianceCandidateStory';
export const metadata: Metadata = { title:'Rupert Pagi Shaw for Kalahooska | Alliance 2068', description:'Rupert Pagi Shaw’s 2068 plan for forestry, local power, resilient connections and communities with a future.' };
const story: CandidateStory = {
 name:'Rupert Pagi Shaw', region:'Kalahooska', portrait:'/images/pagi-2064.png', hero:'/images/kalahooska/forest.jpg', heroAlt:'Sunlight breaking through a dense working forest', theme:'kalahooska',
 eyebrow:'Rupert Pagi Shaw for Kalahooska · 2068', headline:'Rooted here.', accent:'Ready to grow.', deck:'Keep our character. Build our confidence. Let local effort travel further.', belief:'“Growth should leave a place stronger than it found it.”',
 introduction:['Kalahooska taught me that stewardship and enterprise are partners. A well managed forest provides work today because somebody cared about tomorrow. The same principle should guide public life.','I want young people to inherit real choices here: a skilled job, a home within reach and services that do not disappear with the next budget cycle. Local people understand this land. National government should trust that knowledge and keep its promises.'],
 promise:'Kalahooska will be heard, and every promise made here will be visible.', eventHref:'/events/#upcoming', eventLabel:'Meet the Alliance', featureImage:'/images/events/ambrosia-fields.jpg', featureAlt:'A rural road linking fields, homes and distant communities',
 chapters:[
  {label:'Working forests',title:'More value from every tree.',intro:'Our natural wealth should support skilled work and long term stewardship close to home.',points:[['Move up the value chain','Support open investment in engineered timber, furniture, biomass byproducts and modern mills where demand and sustainable supply support a business case. Connect firms to equipment expensing and export certification.'],['Harvest, restore, repeat','Set transparent regional forest plans based on independent inventories. Require replanting, habitat protection and funded restoration, with results published by catchment and concession.'],['Open contracts to local firms','Publish forestry, road and public building pipelines early. Break suitable contracts into accessible lots and enforce prompt payment without weakening safety or value tests.']]},
  {label:'Connections',title:'Distance should not decide your future.',intro:'A failed bridge or unreliable signal can isolate a family, a clinic and a business at once.',points:[['Keep essential roads open','Publish a condition audit of bridges, slopes and freight routes, then fund maintenance by safety and isolation risk. Show the responsible agency and next milestone.'],['Reliable digital access','Tender support only where the market cannot provide service, paying for tested speed and reliability. Keep telephone and in person access to essential public services.'],['Transport built around real journeys','Coordinate regional services around work, school and medical appointments. Use competitive essential route contracts where demand cannot sustain a commercial service.']]},
  {label:'Local power',title:'Decisions closer to the people living with them.',intro:'Regional authority must come with the revenue and responsibility to make it real.',points:[['A practical regional settlement','Seek multi year powers over local transport, skills and land management, with funding responsibilities written into law and independently audited.'],['Keep project value here','Return a transparent share of royalties from nationally significant resource projects to host communities for durable infrastructure and skills.'],['Open government by default','Publish contracts, land decisions and delivery dashboards in usable form, with assisted access for residents who are offline. Protect personal casework.']]},
  {label:'A life here',title:'A reason to stay. A reason to return.',intro:'Local pride lasts when people can build an independent life around it.',points:[['Homes where services can support them','Plan suitable housing in existing towns alongside water, schools and transport. Invite smaller builders to compete and publish approval times.'],['Skills tied to a real job','Build paid pathways in forestry, engineering, care and construction with shared apprenticeship administration for small employers.'],['Care within reach','Coordinate visiting clinics, primary care and patient transport, and publish regional access times. Support unpaid caregivers through the national respite commitment.']]}
 ]
};
export default function RupertPagiShaw(){return <AllianceCandidateStory story={story}/>;}
