import type { Metadata } from 'next';
import type { CandidateStory } from '../components/AllianceCandidateStory';
import PagiCampaign from './PagiCampaign';
export const metadata: Metadata = { title:'Rupert Pagi Shaw for Kalahooska | Alliance 2068', description:'Rupert Pagi Shaw’s 2068 plan for forestry, local power, resilient connections and communities with a future.' };
const story: CandidateStory = {
 name:'Rupert Pagi Shaw', region:'Kalahooska', portrait:'/images/pagi-2064.png', hero:'/images/candidate-review/kalahooska/forest-hd.jpg', heroAlt:'Mist drifting across a dense green conifer forest', theme:'kalahooska',
 eyebrow:'Rupert Pagi Shaw for Kalahooska · 2068', headline:'Rooted here.', accent:'Ready to grow.', deck:'Keep our character. Build our confidence. Let local effort travel further.', belief:'“Growth should leave a place stronger than it found it.”',
 introduction:['In Kalahooska, stewardship and enterprise belong together. A well-managed forest can support skilled work and local businesses while renewing the resource they depend on. I want government to bring that same long view to roads, homes and public services.','A new mill is only part of the story. Its workers need somewhere to live, its suppliers need a dependable road and the surrounding towns need schools and care they can count on. My plan connects those needs, with more practical decisions made close to the people who live with them.'],
 promise:'Kalahooska will be heard, and every promise made here will be visible.', eventHref:'/events/#upcoming', eventLabel:'Meet the Alliance', featureImage:'/images/kalahooska/forest-connections.jpg', featureAlt:'An aerial view of a winding road connecting dense forested hills in morning mist',
 planTitle:'A working forest. A thriving region.',
 planIntro:'Make more of Kalahooska’s resources here, keep its towns connected and create room to live near the work. National support should strengthen local enterprise and local responsibility, with restoration and maintenance built into the cost.',
 commitmentCopy:['I will seek regional agreements that name the authority, the funding and the next decision. Forest renewal, road maintenance and housing capacity should be visible together, so a project is judged by what it makes possible across Kalahooska.','Local power must be accountable power. I will defend independent audit, open contracts and a fair route to challenge decisions. Constituency help will be available regardless of political views, and progress reports will include the promises still waiting for an answer.'],
 invitationTitle:'Bring the view from your town.',
 invitationCopy:'What keeps a local firm from growing? Which connection cannot be relied on? Where could a new home make sense? Bring Kalahooska’s practical knowledge into the Alliance conversation.',
 chapters:[
  {label:'Working forests',title:'More value from every tree.',intro:'Our natural wealth should support skilled work and long-term stewardship close to home.',points:[['Turn more timber into finished products','Support open investment in engineered timber, furniture, useful byproducts and modern mills where demand and sustainable supply support a business case. Connect firms to the Alliance’s equipment expensing and export certification proposals, with competition deciding who earns the order.'],['Harvest, restore, repeat','Set transparent regional forest plans based on independent inventories. Require replanting, habitat protection and funded restoration, with results published by catchment and concession.'],['Open contracts to local firms','Publish forestry, road and public building pipelines early. Break suitable contracts into accessible lots and enforce prompt payment without weakening safety or value tests.']]},
  {label:'Connections',title:'Distance should not decide your future.',intro:'A failed bridge or unreliable signal can isolate a family, a clinic and a business at once.',points:[['Keep essential roads open','Publish a condition audit of bridges, slopes and freight routes, then fund maintenance by safety and isolation risk. Coordinate heavy freight with road capacity and repair plans. Show the responsible agency, disruption arrangements and next milestone.'],['Reliable digital access','Tender support only where the market cannot provide service, paying for tested speed and reliability. Give clinics and essential services backup connections. Keep telephone and in-person access to public services.'],['Transport built around real journeys','Coordinate regional services around work, school and medical appointments. Use competitive essential-route contracts where demand cannot sustain a commercial service, with public reliability standards and clear disruption information.']]},
  {label:'Local power',title:'Decisions closer to the people living with them.',intro:'Regional authority must come with the revenue and responsibility to make it real.',points:[['A practical regional settlement','Seek lasting regional powers over local transport, skills and land management, backed by multi-year budgets. Set funding responsibilities in law and retain independent audit. Residents should know which authority can act and which account pays.'],['Keep project value here','Return a transparent share of royalties from nationally significant resource projects to host communities for durable infrastructure and skills. Publish receipts and their use, and avoid making essential services depend on a single volatile revenue source.'],['Open government by default','Publish contracts, land decisions and delivery dashboards in usable form, with assisted access for residents who are offline. Protect personal casework and an independent route to challenge a public decision.']]},
  {label:'A life here',title:'A reason to stay. A reason to return.',intro:'Local pride lasts when people can build an independent life around it.',points:[['Homes where services can support them','Plan suitable housing in existing towns alongside water, schools and transport. Invite smaller builders to compete and publish approval times.'],['Skills tied to a real job','Build paid pathways in forestry, engineering, care and construction with shared apprenticeship administration for small employers.'],['Care within reach','Coordinate visiting clinics, primary care and patient transport, and publish regional access times. Support unpaid caregivers through the national respite commitment.']]}
 ]
};
export default function RupertPagiShaw(){return <PagiCampaign story={story}/>;}
