import type { Metadata } from 'next';
import AllianceCandidateStory, { CandidateStory } from '../components/AllianceCandidateStory';
export const metadata: Metadata = { title:'Mathieu Jeon for Pleucadeuc | Alliance 2068', description:'Mathieu Jeon’s 2068 plan for the southern rail corridor, station communities, coastal resilience and Gallic life.' };
const story: CandidateStory = {
 name:'Mathieu Jeon', region:'Pleucadeuc', portrait:'/images/mathieu.jpg', hero:'/images/pleucadeuc/rail.jpg', heroAlt:'A modern high speed train crossing mountain country', theme:'pleucadeuc',
 eyebrow:'Mathieu Jeon for Pleucadeuc · 2068', headline:'Closer to opportunity.', accent:'Closer to home.', deck:'Faster connections. Stronger towns. A southern region confident in its own voice.', belief:'“Staying home should never mean standing still.”',
 introduction:['I was born and raised in Pleucadeuc. I know the quiet pride of a place with its own language, coastline and way of life. I also know why talented young people look north when the journey to study or work feels longer every year.','My politics begins with a simple promise: where you come from should be a source of strength, not a limit on your future. Better connections can bring opportunity closer, but only if the homes, apprenticeships and local services arrive with them.'],
 promise:'I will fight for the southern corridor without treating any community as a place the train simply passes.', eventHref:'/events/#southern-line', eventLabel:'The Southern Line', featureImage:'/images/pleucadeuc/rail-map.png', featureAlt:'Illustrated map of rail connections across southern Caprica',
 chapters:[
  {label:'The southern line',title:'Fast rail with a serious delivery plan.',intro:'The Valcartier, Fiévreau and Syon corridor should connect Pleucadeuc to opportunity and connect its towns to one another.',points:[['Publish the route and the test','Commission the engineering, demand, environmental and cost work for a full speed and capacity upgrade. Publish alternatives, benefits by station and an independent value assessment before procurement.'],['Build it in accountable stages','Sequence track, power, signaling and station works around verified milestones. Disclose contract changes and whole life maintenance costs, with parliamentary scrutiny for material overruns.'],['Make the whole journey work','Coordinate regional rail and buses with the fast line, preserve accessible ticket options and set connection standards. A faster trunk route means little if the last service leaves first.']]},
  {label:'Station communities',title:'A stop should become a starting point.',intro:'Rail investment should create homes, apprenticeships and business opportunities in the towns it serves.',points:[['Homes near the station','Zone suitable land for mixed housing with water, schools, safe walking routes and public space planned from the start. Publish infrastructure funding and approval times.'],['Build the skills here','Require open apprenticeship and supplier plans in major rail contracts, tied to recognized qualifications rather than temporary head counts. Help smaller regional firms bid.'],['Make town centers easier to use','Coordinate station renewal with local shops, markets and cultural venues. Keep construction access plans public and support time limited uses for vacant premises.']]},
  {label:'Coast and resilience',title:'Protect the places that hold our memories.',intro:'Pleucadeuc’s coast is home, livelihood and inheritance.',points:[['Plan for the risks we can see','Map erosion, flooding and critical infrastructure exposure, then rank protection by lives, essential services and long term value. Avoid new building in the most dangerous locations.'],['Back the working coast','Improve landing, cold chain and harbor facilities where demand supports them. Keep access terms transparent for independent fishers and enforce science based stocks.'],['A cleaner southern economy','Speed up competitive connections for clean power and industrial investment while protecting valued landscapes through clear rules and local benefit agreements.']]},
  {label:'Gallic life',title:'Keep what makes us. Share it with confidence.',intro:'Language and culture thrive when they are present in ordinary public life and connected to economic opportunity.',points:[['Services people can understand','Maintain meaningful access to Gallic language education and public information where communities use it, with practical standards and published availability.'],['Culture as a living economy','Make licensing simpler for local venues, festivals and creative businesses while keeping safety and neighborhood conditions clear. Connect cultural tourism to local suppliers.'],['A voice between elections','Hold constituency sessions across the corridor and publish themes and follow up actions in accessible formats. Report votes, funding decisions and delivery every quarter.']]}
 ]
};
export default function MathieuJeon(){return <AllianceCandidateStory story={story}/>;}
