import type { Metadata } from 'next';
import AllianceCandidateStory, { CandidateStory } from '../components/AllianceCandidateStory';
export const metadata: Metadata = { title:'Mathieu Jeon for Pleucadeuc | Alliance 2068', description:'Mathieu Jeon’s 2068 plan for the southern rail corridor, station communities, coastal resilience and Gallic life.' };
const story: CandidateStory = {
 name:'Mathieu Jeon', region:'Pleucadeuc', portrait:'/images/mathieu.jpg', hero:'/images/pleucadeuc/rail.jpg', heroAlt:'A modern high-speed train crossing mountain country', theme:'pleucadeuc',
 eyebrow:'Mathieu Jeon for Pleucadeuc · 2068', headline:'Closer to opportunity.', accent:'Closer to home.', deck:'Faster connections. Stronger towns. A southern region confident in its own voice.', belief:'“Staying home should never mean standing still.”',
 introduction:['I was born and raised in Pleucadeuc. Its language, coastline and towns are part of what home means to me. I want the southern line to connect that home to more opportunities, not turn it into somewhere people simply travel through.','Faster trains are the beginning of the case, not the whole case. A station should help a business find customers, connect someone to a course or a shift, and make room for homes close to the journey. I will argue for the corridor as part of a wider plan for our towns, with each stage tested against demand and its full cost.'],
 promise:'I will fight for the southern corridor without treating any community as a place the train simply passes.', eventHref:'/events/#southern-line', eventLabel:'The Southern Line', featureImage:'/images/pleucadeuc/rail-map.png', featureAlt:'Illustrated map of rail connections across southern Caprica',
 planTitle:'A faster line. More life around it.',
 planIntro:'The southern corridor belongs in the Alliance’s national infrastructure plan. My case joins the railway to station homes, useful skills, coastal livelihoods and Gallic life, so the benefits reach beyond the platform.',
 commitmentCopy:['I will make the case for Valcartier, Fiévreau and Syon with the evidence open: demand, alternatives, journey times and the full cost of operating and maintaining the line. Staging must mean a clear next decision, not a promise pushed indefinitely into the future.','I will report how the railway connects to local buses, housing and work, and hold constituency conversations beyond the main stations. Pleucadeuc deserves a representative who can argue for national investment and question its delivery with equal determination.'],
 invitationTitle:'Where should the southern line take us?',
 invitationCopy:'Join The Southern Line conversation at Valcartier Central. Bring your journey, your town’s priorities and your questions about the cost, the connections and the homes around the stations.',
 chapters:[
  {label:'The southern line',title:'Fast rail with a serious delivery plan.',intro:'The Valcartier, Fiévreau and Syon corridor should connect Pleucadeuc to opportunity and connect its towns to one another.',points:[['Publish the route and the test','Complete the engineering, demand, environmental and cost work for the proposed high-speed upgrade. Publish alternatives, journey-time gains by station and an independent value assessment before procurement. Each major commitment must pass funding and passenger-demand checks.'],['Build it in accountable stages','Sequence track, power, signaling and station works around verified milestones. Disclose contract changes, operating subsidies and whole-life maintenance costs, with parliamentary scrutiny for material overruns.'],['Make the whole journey work','Coordinate regional rail and buses with the fast line and set connection standards. Seek participation in the Alliance’s common payment account and weekly fare cap, while retaining cash or assisted options. A faster trunk route means little if the last local service leaves first.']]},
  {label:'Station communities',title:'A stop should become a starting point.',intro:'Rail investment should create homes, apprenticeships and business opportunities in the towns it serves.',points:[['Homes near the station','Seek local planning agreements for mixed housing on suitable land near stations, with water, schools, safe walking routes and public space planned from the start. Publish infrastructure funding and approval times so the promise of new homes has a delivery route.'],['Build the skills here','Require open apprenticeship and supplier plans in major rail contracts, tied to recognized qualifications rather than temporary head counts. Help smaller regional firms bid.'],['Make town centers easier to use','Coordinate station renewal with local shops, markets and cultural venues. Keep construction access plans public and support time-limited uses for vacant premises.']]},
  {label:'Coast and resilience',title:'Protect the places that hold our memories.',intro:'Pleucadeuc’s coast is home, livelihood and inheritance.',points:[['Plan for the risks we can see','Map erosion, flooding and critical infrastructure exposure, then rank protection by lives, essential services and long-term value. Avoid new building in the most dangerous locations.'],['Back the working coast','Improve landing, cold-chain and harbor facilities where demand supports them. Keep access terms transparent for independent fishers. Base catch limits on independent stock assessments and enforce the rules against illegal fishing.'],['A cleaner southern economy','Speed up competitive connections for clean power and industrial investment while protecting valued landscapes through clear rules and local benefit agreements.']]},
  {label:'Gallic life',title:'Keep what makes us. Share it with confidence.',intro:'Language and culture thrive when they are present in ordinary public life and connected to economic opportunity.',points:[['Services people can understand','Maintain meaningful access to Gallic-language education and public information where communities use it, alongside proficiency in the national language. Publish practical service standards and availability.'],['Culture as a living economy','Make licensing simpler for local venues, festivals and creative businesses while keeping safety and neighborhood conditions clear. Connect cultural tourism to local suppliers.'],['A voice between elections','Hold constituency sessions across the corridor and publish themes and follow-up actions in accessible formats. Report votes, funding decisions and delivery every quarter.']]}
 ]
};
export default function MathieuJeon(){return <AllianceCandidateStory story={story}/>;}
