import Link from 'next/link';
import { PlatformHeader } from '../platform/PlatformChrome';
import CandidateActions from '../components/CandidateActions';
import './myrati-review.css';

const policies = [
 {id:'trade',number:'01',name:'Work that stays here',title:'An open port. A stronger local economy.',links:[['economy','Enterprise & fair competition'],['foreign-policy','Trade & the wider world']],items:[
  ['Bring Port Aaron’s next phase into focus', 'Seek a published delivery review of the Prosper Myrati port program: deep-water berths, container handling, shipbuilding and repair facilities, and the mainland trade corridor. Separate completed work from funded commitments and proposals still awaiting approval. Prioritize the next investments by demand, local employment and whole-life cost.'],
  ['A Free Trade Port with clear public rules', 'Pursue Free Trade Port status with simpler customs procedures, transparent eligibility and time-limited investment incentives. Retain labor, environmental and anti-smuggling standards. Publish the cost of concessions and review whether they produce additional investment and durable jobs rather than simply subsidizing activity that would happen anyway.'],
  ['Give local firms a way into the work', 'Publish upcoming contracts in accessible lots where practical, offer supplier briefings and enforce prompt payment. Connect maritime employers with local training providers for paid apprenticeships. Small exporters should have access to customs advice, shared logistics and cold-chain facilities where a business case supports them.'],
 ]},
 {id:'connections',number:'02',name:'An island within reach',title:'Better journeys. More possibilities.',links:[['infrastructure','Infrastructure & reliable power']],items:[
  ['Finish the journey beyond the terminal', 'Coordinate port and airport investment with the roads, rail links and local services that connect them to communities. Publish a single capital plan with responsible agencies, dependencies and maintenance costs. A new terminal should not leave passengers or freight waiting at the gate for the next connection.'],
  ['An airport built around real demand', 'Review the proposed second runway, cargo facilities and passenger expansion against updated traffic forecasts, safety requirements and environmental assessments. Sequence construction to meet demand and protect public finances. Encourage competing services and transparent airport charges rather than promising routes government cannot guarantee.'],
  ['Make island travel dependable', 'Work with operators on coordinated timetables and clear disruption information. Where an essential connection cannot support itself commercially, use a transparent, competitively tendered service contract with measurable reliability standards. Include access to education and medical appointments in the assessment of public need.'],
 ]},
 {id:'opportunity',number:'03',name:'A future to come home to',title:'Learn widely. Build a life here.',links:[['housing','Homes & independence'],['education','Education & practical skills'],['healthcare','Care within reach']],items:[
  ['Protect the scholarship pathway', 'Back the Prosper Myrati program’s provision for 1,200 annual student scholarships, covering academic, technical and professional study. Publish eligibility, selection criteria and annual award data. Assess travel and living costs alongside tuition so opportunity is not reserved for families who can already afford to leave.'],
  ['Make returning a real choice', 'Build a voluntary placement network linking students and graduates with Myratian employers, schools, clinics and maritime firms. Offer paid work experience with published terms. Recognize relevant qualifications and connect returning professionals with local opportunities, without imposing punitive obligations on students who study away.'],
  ['Homes and services that grow together', 'Pair port and airport growth with homes on suitable serviced sites near jobs and transport, using the Alliance’s regional housing agreements. Plan water, school and clinic capacity alongside construction. Seek a funded island care-access plan, including referral transport and visiting services, before activating national waiting-time guarantees. Report outstanding reconstruction needs separately, so existing residents can see when their homes and services will be restored.'],
 ]},
 {id:'voice',number:'04',name:'A Myrati for all of us',title:'Our identity. Everyone’s dignity.',links:[['civil-liberties','Equal citizenship & accountable power']],items:[
  ['Keep decisions close to the island', 'Defend Myrati’s language, schools and regional institutions. Seek clear agreements giving regional authorities practical control over local tourism and transport, with funding responsibilities spelled out. National investment should strengthen local capacity, not make every decision depend on a distant office.'],
  ['The same fair rules for everyone', 'Support community policing, independent complaints handling and due process. Protect peaceful assembly and political disagreement. Public services, grants and constituency assistance must never depend on how someone voted. Safety is a shared responsibility, not a test of political loyalty.'],
  ['A public account of the island plan', 'Publish quarterly updates on port and airport work, scholarship access and unresolved service needs. Show what is complete, funded or still proposed. Invite questions across political traditions and report follow-up actions. JB’s role is to negotiate with responsible authorities and scrutinize their delivery, with no claim of personal control over every contract.'],
 ]},
];
const image = (name:string) => `/images/myrati/${name}.jpg`;
export default function Myrati(){return <div className="myr68">
 <a className="campaign-skip" href="#main">Skip to content</a>
 <PlatformHeader/><nav className="candidate-localbar" aria-label="Myrati campaign"><a href="#plan">Our island plan</a><a href="#jb">Meet JB</a><a href="#join">Take part</a></nav>
 <main id="main">
  <section className="myr-hero"><img src={image('coast')} alt="A sunny coastal community beside a sheltered bay" fetchPriority="high"/><div className="myr-width"><p className="campaign-label">JB Stoner · Moderate Reform · Myrati 2068</p><h1>Proud of Myrati.<br/><em>Open to tomorrow.</em></h1><p className="myr-hero-text">An island open for business.<br/>A home with room for all of us.</p><a className="myr-button" href="#island-route">See how the island plan connects <span aria-hidden="true">↓</span></a><div className="myr-hero-bottom"><span>JB STONER / FOR MYRATI</span><span>OUR ISLAND. OUR FUTURE.</span></div></div></section>
  <section className="myr-welcome myr-width" id="jb"><div className="myr-portrait"><img src="/images/stoner.png" alt="JB Stoner, Moderate Reform candidate for Myrati" loading="lazy"/><div><strong>JB Stoner</strong><span>YOUR VOICE FOR MYRATI</span></div></div><div className="myr-welcome-copy"><p className="campaign-label">An invitation to every Myratian</p><h2>We share more<br/>than an island.<br/><em>We share a future.</em></h2><p className="myr-lead">You do not have to share a political history to want a better life for the place you call home.</p><p>JB’s campaign is about what we can build together: skilled work at Port Aaron, dependable connections, a fair chance to study and communities where our language and institutions flourish.</p><p>He backed the Prosper Myrati program. Now his task is to press for its promises to become useful, lasting results, and to answer for the work still ahead. Every neighborhood deserves a hearing. Every family deserves a place in the island’s next chapter.</p><Link className="myr-link" href="/team/#stoner">Meet the Alliance team <span aria-hidden="true">↗</span></Link></div></section>
  <section className="myr-route" id="island-route" aria-labelledby="myr-route-title"><div className="myr-width"><div className="myr-route-heading"><p className="campaign-label">The island opportunity route</p><h2 id="myr-route-title">The world at our door.<br/><em>The value stays here.</em></h2><p>Growth is not a photograph of a new terminal. It is an order for a local firm, a skill worth learning and the freedom to make a life on the island.</p></div><div className="myr-route-line"><a href="#trade"><span className="myr-route-stop">01</span><small>OPEN THE MARKET</small><h3>A way to trade.</h3><p>Port Aaron, competitive access and a place for local suppliers.</p><span className="myr-route-action">Explore the port plan <b aria-hidden="true">↗</b></span></a><a href="#connections"><span className="myr-route-stop">02</span><small>COMPLETE THE JOURNEY</small><h3>A dependable link.</h3><p>Port, airport, roads and rail planned as one working system.</p><span className="myr-route-action">Follow the connections <b aria-hidden="true">↗</b></span></a><a href="#opportunity"><span className="myr-route-stop">03</span><small>BUILD THE LIFE</small><h3>A reason to return.</h3><p>Scholarships, paid experience, homes and care within reach.</p><span className="myr-route-action">See the opportunity plan <b aria-hidden="true">↗</b></span></a></div><div className="myr-route-foundation"><span>THE FOUNDATION, AT EVERY STOP</span><Link href="#voice">Our language. Equal citizenship. Government that answers to everyone. <b aria-hidden="true">→</b></Link></div></div></section>
  <section className="myr-port myr-width"><div className="myr-port-heading"><p className="campaign-label">Port Aaron · From investment to opportunity</p><h2>More than a port.<br/><em>A way forward.</em></h2></div><div className="myr-port-grid"><figure><img src={image('port')} alt="A container ship alongside large cargo cranes" loading="lazy"/><figcaption>BUILD CONNECTIONS THAT CREATE OPPORTUNITY AT HOME.</figcaption></figure><div><p className="myr-lead">“We export Myratian goods, and import opportunities.”</p><p>A berth matters when it brings another order. A repair dock matters when it supports a skilled job. A trade corridor matters when a small producer can reach a new customer.</p><p>JB wants the next phase of Prosper Myrati judged by those everyday results, with open contracts, clear costs and a route for local businesses to take part.</p><ol><li><span>01</span><div><strong>Connect the island</strong><p>Port, airport, road and rail planned together.</p></div></li><li><span>02</span><div><strong>Build local capability</strong><p>Supplier access and paid maritime training.</p></div></li><li><span>03</span><div><strong>Show the public the progress</strong><p>What is finished, what is funded, what comes next.</p></div></li></ol><a className="myr-link" href="#trade">Read the trade commitments <span aria-hidden="true">↗</span></a></div></div></section>
  <section className="myr-journeys"><div className="myr-width"><div className="myr-journeys-title"><p className="campaign-label">Beyond the horizon. Close to home.</p><h2>The world should feel closer.<br/><em>Home should stay within reach.</em></h2></div><div className="myr-journey-cards"><article><img src={image('airport')} alt="Travelers waiting beside large airport windows" loading="lazy"/><div><span>CONNECTIONS THAT COUNT</span><h3>A visit. An appointment.<br/>A new beginning.</h3><p>Island travel is not just about visitors. It is about seeing family, reaching a specialist, meeting a customer and getting home again. Reliability belongs at the heart of the transport plan.</p><a className="myr-link" href="#connections">The connections plan <span aria-hidden="true">↗</span></a></div></article><article><img src={image('students')} alt="Students working together in a library study area" loading="lazy"/><div><span>AMBITION WITHOUT A ONE-WAY TICKET</span><h3>Go and learn.<br/>Have a reason to return.</h3><p>Protect the scholarship pathway. Connect study with paid experience and work on the island. Leaving to learn should open up your choices, not close the door on a life in Myrati.</p><a className="myr-link" href="#opportunity">The opportunity plan <span aria-hidden="true">↗</span></a></div></article></div></div></section>
  <section className="myr-belong myr-width"><p className="campaign-label">A confident island</p><h2>Our differences belong<br/>in the conversation.<br/><em>Our future belongs to all of us.</em></h2><div><p>Myrati can cherish its identity and look outward. We can disagree about politics and still expect the same fair treatment, safe streets and dependable services.</p><p>JB stands for patient, practical government: listen carefully, respect the rules and keep doing the work. Progress should reach your community because you live here, not because you voted a particular way.</p></div><a className="myr-link" href="#voice">A fair hearing for every community <span aria-hidden="true">↗</span></a></section>
  <section className="myr-plan" id="plan"><div className="myr-width"><div className="myr-plan-title"><div><p className="campaign-label">The Myrati plan · 2068 to 2072</p><h2>A bigger horizon.<br/><em>A practical course.</em></h2></div><p>Four local chapters. Twelve commitments.<br/>The proposals, the safeguards and the national policy behind each one.</p></div><nav className="myr-plan-index" aria-label="Myrati policy chapters">{policies.map(p=><a key={p.id} href={`#${p.id}`}><span>{p.number}</span>{p.name}<b aria-hidden="true">↓</b></a>)}</nav><div className="myr-policy-grid">{policies.map(p=><article key={p.id} id={p.id}><span className="myr-policy-number">{p.number}</span><p className="campaign-label">{p.name}</p><h3>{p.title}</h3>{p.items.map(([title,copy],index)=><details key={title} open={index===0}><summary>{title}<span aria-hidden="true">↓</span></summary><p>{copy}</p></details>)}<div className="myr-policy-pathways"><p>THE NATIONAL COMMITMENTS</p>{p.links.map(([slug,label])=><Link href={`/platform/${slug}/`} key={slug}>{label}<span aria-hidden="true">↗</span></Link>)}</div></article>)}</div><aside className="myr-public-account" aria-labelledby="myr-account-title"><div><p className="campaign-label">The test for every announcement</p><h3 id="myr-account-title">Proposed is not funded.<br/><em>Funded is not finished.</em></h3></div><div><p>JB will seek a quarterly public account that names the responsible authority, separates approved funding from proposals, and shows what people can actually use. No ribbon-cutting should stand in for a working service.</p><p>Major investment must pass independent appraisal and fit the Alliance’s fiscal rules. Publish the price of incentives, borrowing and maintenance as clearly as the promised benefits.</p><Link className="myr-link" href="/platform/economy/">The financial discipline behind the plan <span aria-hidden="true">↗</span></Link></div></aside><div className="myr-national"><p>Homes. Enterprise. Infrastructure. Services. Freedom.<br/>One island plan, part of the Alliance’s five connected priorities.</p><Link className="myr-link" href="/manifesto/caprica-freedom-to-build-2068.pdf" target="_blank" rel="noreferrer">The full Alliance manifesto · PDF <span aria-hidden="true">↗</span></Link></div></div></section>
  <section className="myr-join myr-width" id="join"><div><p className="campaign-label">Open seas. Open conversation.</p><h2>Bring your hopes.<br/>Bring your questions.<br/><em>Bring your Myrati.</em></h2></div><div><p>A stronger island starts with the people who know it. Join the Port Aaron forum to talk about work, trade and the connections our communities need.</p><p>There is room in this conversation for people who have never voted for JB, as well as those who have stood with him before.</p><Link className="myr-button" href="/events/#open-seas-open-markets">Find the Port Aaron forum <span aria-hidden="true">↗</span></Link><CandidateActions name="JB Stoner" region="Myrati" commitments={['Seek a published delivery review of Port Aaron and the Prosper Myrati program, with open supplier access and independent cost tests.','Coordinate port, airport, road and rail investment around verified demand and funded maintenance.','Back 1,200 annual student scholarships, paid placement pathways and homes with services planned alongside them.','Defend island institutions and equal citizenship; publish a quarterly account that distinguishes proposals, funded work and working services.']}/></div></section>
 </main>
 <footer className="myr-footer myr-width"><Link className="myr-brand" href="/jb-stoner/"><img src="/images/mr-logo.png" alt="Moderate Reform" width="58" height="36"/><span>JB STONER<small>OUR ISLAND. OUR FUTURE.</small></span></Link><Link href="/">The Alliance ↗</Link><a href="#main">Back to top ↑</a></footer>
</div>;}
