import Link from 'next/link';

const policies = [
 {id:'trade',number:'01',name:'Work that stays here',title:'An open port. A stronger local economy.',items:[
  ['Bring Port Aaron’s next phase into focus', 'Seek a published delivery review of the Prosper Myrati port program: deep-water berths, container handling, shipbuilding and repair facilities, and the mainland trade corridor. Separate completed work from funded commitments and proposals still awaiting approval. Prioritize the next investments by demand, local employment and whole-life cost.'],
  ['A Free Trade Port with clear public rules', 'Pursue Free Trade Port status with simpler customs procedures, transparent eligibility and time-limited investment incentives. Retain labor, environmental and anti-smuggling standards. Publish the cost of concessions and review whether they produce additional investment and durable jobs rather than simply subsidizing activity that would happen anyway.'],
  ['Give local firms a way into the work', 'Publish upcoming contracts in accessible lots where practical, offer supplier briefings and enforce prompt payment. Connect maritime employers with local training providers for paid apprenticeships. Small exporters should have access to customs advice, shared logistics and cold-chain facilities where a business case supports them.'],
 ]},
 {id:'connections',number:'02',name:'An island within reach',title:'Better journeys. More possibilities.',items:[
  ['Finish the journey beyond the terminal', 'Coordinate port and airport investment with the roads, rail links and local services that connect them to communities. Publish a single capital plan with responsible agencies, dependencies and maintenance costs. A new terminal should not leave passengers or freight waiting at the gate for the next connection.'],
  ['An airport built around real demand', 'Review the proposed second runway, cargo facilities and passenger expansion against updated traffic forecasts, safety requirements and environmental assessments. Sequence construction to meet demand and protect public finances. Encourage competing services and transparent airport charges rather than promising routes government cannot guarantee.'],
  ['Make island travel dependable', 'Work with operators on coordinated timetables and clear disruption information. Where an essential connection cannot support itself commercially, use a transparent, competitively tendered service contract with measurable reliability standards. Include access to education and medical appointments in the assessment of public need.'],
 ]},
 {id:'opportunity',number:'03',name:'A future to come home to',title:'Learn widely. Build a life here.',items:[
  ['Protect the scholarship pathway', 'Back the Prosper Myrati program’s provision for 1,200 annual student scholarships, covering academic, technical and professional study. Publish eligibility, selection criteria and annual award data. Assess travel and living costs alongside tuition so opportunity is not reserved for families who can already afford to leave.'],
  ['Make returning a real choice', 'Build a voluntary placement network linking students and graduates with Myratian employers, schools, clinics and maritime firms. Offer paid work experience with published terms. Recognize relevant qualifications and connect returning professionals with local opportunities, without imposing punitive obligations on students who study away.'],
  ['Homes and services that grow together', 'Use the Alliance housing program to unlock suitable serviced sites near jobs and transport. Coordinate water, schools and clinics with new development. Report outstanding reconstruction needs separately from new housing plans, so existing residents are not left waiting while attention moves to the next project.'],
 ]},
 {id:'voice',number:'04',name:'A Myrati for all of us',title:'Our identity. Everyone’s dignity.',items:[
  ['Keep decisions close to the island', 'Defend Myrati’s language, schools and regional institutions. Seek clear agreements giving regional authorities practical control over local tourism and transport, with funding responsibilities spelled out. National investment should strengthen local capacity, not make every decision depend on a distant office.'],
  ['The same fair rules for everyone', 'Support community policing, independent complaints handling and due process. Protect peaceful assembly and political disagreement. Public services, grants and constituency assistance must never depend on how someone voted. Safety is a shared responsibility, not a test of political loyalty.'],
  ['A public account, not a victory lap', 'Publish quarterly updates on major projects, scholarship access and unresolved service needs. Invite questions from community groups across political traditions and report follow-up actions. An MP should scrutinize delivery and negotiate with responsible authorities, not claim personal control over every contract or local service.'],
 ]},
];
const image = (name:string) => `/images/myrati/${name}.jpg`;
export default function Myrati(){return <div className="myr68">
 <a className="campaign-skip" href="#main">Skip to content</a>
 <header className="myr-header"><Link className="myr-brand" href="/myrati/"><img src="/images/mr-logo.png" alt="Moderate Reform" width="58" height="36"/><span>JB STONER<small>MYRATI · 2068</small></span></Link><nav aria-label="Myrati campaign"><a href="#plan">Our island plan</a><a href="#jb">Meet JB</a><a href="#join">Take part</a><Link href="/">The Alliance ↗</Link></nav></header>
 <main id="main">
  <section className="myr-hero"><img src={image('coast')} alt="A sunny coastal community beside a sheltered bay" fetchPriority="high"/><div className="myr-width"><p className="campaign-label">JB Stoner · Moderate Reform · Myrati 2068</p><h1>Proud of Myrati.<br/><em>Open to tomorrow.</em></h1><p className="myr-hero-text">Good work. Strong connections.<br/>A future with room for all of us.</p><a className="myr-button" href="#plan">Explore the island plan <span aria-hidden="true">↓</span></a><div className="myr-hero-bottom"><span>OUR ISLAND. OUR FUTURE.</span><span>MYRATI / CAPRICA / 2068</span></div></div></section>
  <section className="myr-welcome myr-width" id="jb"><div className="myr-portrait"><img src="/images/stoner.png" alt="JB Stoner, Moderate Reform candidate for Myrati" loading="lazy"/><div><strong>JB Stoner</strong><span>YOUR VOICE FOR MYRATI</span></div></div><div className="myr-welcome-copy"><p className="campaign-label">An invitation to every Myratian</p><h2>We share more<br/>than an island.<br/><em>We share a future.</em></h2><p className="myr-lead">You do not have to share a political history to want a better life for the place you call home.</p><p>JB’s campaign is about what we can build together: skilled work at Port Aaron, dependable connections, a fair chance to study and communities where our language and institutions flourish.</p><p>He backed the Prosper Myrati program. Now his task is to press for its promises to become useful, lasting results, and to answer for the work still ahead. Every neighborhood deserves a hearing. Every family deserves a place in the island’s next chapter.</p><Link className="myr-link" href="/team/#stoner">Meet the Alliance team <span aria-hidden="true">↗</span></Link></div></section>
  <section className="myr-compass"><div className="myr-width"><p className="campaign-label">A shared direction</p><div><a href="#trade"><small>OPEN MARKETS</small><strong>Work here.</strong><span>Trade that creates island opportunity ↗</span></a><a href="#opportunity"><small>OPEN DOORS</small><strong>Grow here.</strong><span>Skills, homes and a reason to return ↗</span></a><a href="#voice"><small>OPEN GOVERNMENT</small><strong>Belong here.</strong><span>A proud identity. A fair hearing. ↗</span></a></div></div></section>
  <section className="myr-port myr-width"><div className="myr-port-heading"><p className="campaign-label">Port Aaron · From investment to opportunity</p><h2>More than a port.<br/><em>A way forward.</em></h2></div><div className="myr-port-grid"><figure><img src={image('port')} alt="A container ship alongside large cargo cranes" loading="lazy"/><figcaption>BUILD CONNECTIONS THAT CREATE OPPORTUNITY AT HOME.</figcaption></figure><div><p className="myr-lead">“We export Myratian goods, and import opportunities.”</p><p>A berth matters when it brings another order. A repair dock matters when it supports a skilled job. A trade corridor matters when a small producer can reach a new customer.</p><p>JB wants the next phase of Prosper Myrati judged by those everyday results, with open contracts, clear costs and a route for local businesses to take part.</p><ol><li><span>01</span><div><strong>Connect the island</strong><p>Port, airport, road and rail planned together.</p></div></li><li><span>02</span><div><strong>Build local capability</strong><p>Supplier access and paid maritime training.</p></div></li><li><span>03</span><div><strong>Show the public the progress</strong><p>What is finished, what is funded, what comes next.</p></div></li></ol><a className="myr-link" href="#trade">Read the trade commitments <span aria-hidden="true">↗</span></a></div></div></section>
  <section className="myr-journeys"><div className="myr-width"><div className="myr-journeys-title"><p className="campaign-label">Beyond the horizon. Close to home.</p><h2>The world should feel closer.<br/><em>Home should stay within reach.</em></h2></div><div className="myr-journey-cards"><article><img src={image('airport')} alt="Travelers waiting beside large airport windows" loading="lazy"/><div><span>CONNECTIONS THAT COUNT</span><h3>A visit. An appointment.<br/>A new beginning.</h3><p>Island travel is not just about visitors. It is about seeing family, reaching a specialist, meeting a customer and getting home again. Reliability belongs at the heart of the transport plan.</p><a className="myr-link" href="#connections">The connections plan <span aria-hidden="true">↗</span></a></div></article><article><img src={image('students')} alt="Students working together in a library study area" loading="lazy"/><div><span>AMBITION WITHOUT A ONE-WAY TICKET</span><h3>Go and learn.<br/>Have a reason to return.</h3><p>Protect the scholarship pathway. Connect study with paid experience and work on the island. Leaving to learn should open up your choices, not close the door on a life in Myrati.</p><a className="myr-link" href="#opportunity">The opportunity plan <span aria-hidden="true">↗</span></a></div></article></div></div></section>
  <section className="myr-belong myr-width"><p className="campaign-label">A confident island</p><h2>Our differences belong<br/>in the conversation.<br/><em>Our future belongs to all of us.</em></h2><div><p>Myrati can cherish its identity and look outward. We can disagree about politics and still expect the same fair treatment, safe streets and dependable services.</p><p>JB stands for patient, practical government: listen carefully, respect the rules and keep doing the work. Progress should reach your community because you live here, not because you voted a particular way.</p></div><a className="myr-link" href="#voice">A fair hearing for every community <span aria-hidden="true">↗</span></a></section>
  <section className="myr-plan" id="plan"><div className="myr-width"><div className="myr-plan-title"><div><p className="campaign-label">The Myrati plan · 2068 to 2072</p><h2>A bigger horizon.<br/><em>A practical course.</em></h2></div><p>Four priorities, twelve commitments.<br/>Open the proposals for the detail behind the promise.</p></div><div className="myr-policy-grid">{policies.map(p=><article key={p.id} id={p.id}><span className="myr-policy-number">{p.number}</span><p className="campaign-label">{p.name}</p><h3>{p.title}</h3>{p.items.map(([title,copy])=><details key={title}><summary>{title}<span aria-hidden="true">↓</span></summary><p>{copy}</p></details>)}</article>)}</div><div className="myr-national"><p>One island plan, part of a shared national program.<br/>Read the Alliance’s full proposals for homes, enterprise and accountable government.</p><Link className="myr-link" href="/manifesto/caprica-freedom-to-build-2068.pdf" target="_blank" rel="noreferrer">The full Alliance manifesto <span aria-hidden="true">↗</span></Link></div></div></section>
  <section className="myr-join myr-width" id="join"><div><p className="campaign-label">Open seas. Open conversation.</p><h2>Bring your hopes.<br/>Bring your questions.<br/><em>Bring your Myrati.</em></h2></div><div><p>A stronger island starts with the people who know it. Join the Port Aaron forum to talk about work, trade and the connections our communities need.</p><p>There is room in this conversation for people who have never voted for JB, as well as those who have stood with him before.</p><Link className="myr-button" href="/events/#open-seas-open-markets">Find the Port Aaron forum <span aria-hidden="true">↗</span></Link></div></section>
 </main>
 <footer className="myr-footer myr-width"><Link className="myr-brand" href="/myrati/"><img src="/images/mr-logo.png" alt="Moderate Reform" width="58" height="36"/><span>JB STONER<small>OUR ISLAND. OUR FUTURE.</small></span></Link><Link href="/">The Alliance ↗</Link><a href="#main">Back to top ↑</a></footer>
</div>;}
